import { StatutoryRule, ProductCategory, RuleCategory } from '../types';

export const STATUTORY_RULESET_VERSION = 'DCA.DCR.2026.1-VERIFIED';

export const CRITICAL_RULE_CATEGORIES: RuleCategory[] = [
  'PRICING_MRP',
  'CONSUMER_CARE',
  'DATES_EXPIRY',
  'SAFETY_WARNINGS',
  'STANDARDS_QUALITY',
];

export function resolveRuleCategory(ruleId: string, title: string, sectionRef: string): RuleCategory {
  const text = `${ruleId} ${title} ${sectionRef}`.toUpperCase();
  if (text.includes('MRP') || text.includes('PRICE') || text.includes('OVERCHARGE') || text.includes('USP') || text.includes('SALE PRICE')) {
    return 'PRICING_MRP';
  }
  if (text.includes('CONSUMER') || text.includes('GRIEVANCE') || text.includes('CARE') || text.includes('HELPLINE') || text.includes('CUSTOMER')) {
    return 'CONSUMER_CARE';
  }
  if (text.includes('EXPIRY') || text.includes('MFG-DATE') || text.includes('MFGDATE') || text.includes('VALIDITY') || text.includes('SHELF LIFE') || text.includes('SHELFLIFE') || text.includes('DATE OF MANUFACTURE') || text.includes('MONTH AND YEAR')) {
    return 'DATES_EXPIRY';
  }
  if (text.includes('CAUTION') || text.includes('WARNING') || text.includes('HAZARD') || text.includes('ANTIDOTE') || text.includes('SAFETY') || text.includes('REDLINE') || text.includes('TOXICITY') || text.includes('PROHIBITED') || text.includes('HAIRDYE') || text.includes('HEXACHLOROPHENE')) {
    return 'SAFETY_WARNINGS';
  }
  if (text.includes('GERM') || text.includes('PURITY') || text.includes('NUTRIENT') || text.includes('BIS') || text.includes('ISI') || text.includes('POTENCY') || text.includes('STANDARD') || text.includes('STERILE') || text.includes('STERIL')) {
    return 'STANDARDS_QUALITY';
  }
  if (text.includes('PROPERNAME') || text.includes('GENERIC') || text.includes('MEDNAME') || text.includes('DRUGNAME') || text.includes('IDENTITY') || text.includes('MFGNAME') || text.includes('MFG-ADDR') || text.includes('MFGADDR') || text.includes('PREMISES') || text.includes('COO') || text.includes('ORIGIN') || text.includes('IMPORTER') || text.includes('COUNTRY')) {
    return 'IDENTITY_ORIGIN';
  }
  if (text.includes('NETQTY') || text.includes('NET CONTENT') || text.includes('NETCONTENT') || text.includes('NET QUANTITY') || text.includes('MPE') || text.includes('TOLERANCE') || text.includes('PACKSIZE') || text.includes('PACK SIZE')) {
    return 'QUANTITY_MEASUREMENT';
  }
  if (text.includes('INGREDIENT') || text.includes('BOTANICAL') || text.includes('ACTIVEING') || text.includes('VEG') || text.includes('FIBRE') || text.includes('MULTIINGRED') || text.includes('PRESERVATIVE') || text.includes('COLOUR') || text.includes('ALCOHOL')) {
    return 'INGREDIENTS_COMPOSITION';
  }
  if (text.includes('LIC') || text.includes('CIB') || text.includes('REGISTRATION') || text.includes('CERTIFICATE')) {
    return 'LICENSES_REGISTRATIONS';
  }
  return 'IDENTITY_ORIGIN';
}

export function isRuleCritical(rule: StatutoryRule): boolean {
  if (rule.criticality === 'CRITICAL' || rule.severity === 'CRITICAL') {
    return true;
  }
  const cat = rule.ruleCategory || rule.rule_category;
  if (cat && CRITICAL_RULE_CATEGORIES.includes(cat)) {
    return true;
  }
  return false;
}

// ─────────────────────────────────────────────────────────────────────────────
// Category helper groups for new pharmaceutical / device / ASU / homoeo modules
// ─────────────────────────────────────────────────────────────────────────────
const ALL_DRUG_CATEGORIES: ProductCategory[] = [
  'DRUG_GENERAL', 'DRUG_SCHEDULE_G', 'DRUG_SCHEDULE_H',
  'DRUG_SCHEDULE_H1', 'DRUG_SCHEDULE_X', 'DRUG_BIOLOGICAL',
  'DRUG_VETERINARY', 'PHARMACEUTICAL',
];

const SCHEDULE_G_CATEGORIES: ProductCategory[] = ['DRUG_SCHEDULE_G'];
const SCHEDULE_H_CATEGORIES: ProductCategory[] = ['DRUG_SCHEDULE_H'];
const SCHEDULE_H1_CATEGORIES: ProductCategory[] = ['DRUG_SCHEDULE_H1'];
const SCHEDULE_X_CATEGORIES: ProductCategory[] = ['DRUG_SCHEDULE_X'];
const BIOLOGICAL_CATEGORIES: ProductCategory[] = ['DRUG_BIOLOGICAL'];
const VETERINARY_CATEGORIES: ProductCategory[] = ['DRUG_VETERINARY'];

const ASU_CATEGORIES: ProductCategory[] = [
  'AYURVEDIC_MEDICINE', 'SIDDHA_MEDICINE', 'UNANI_MEDICINE',
];

const MEDICAL_DEVICE_CATEGORIES: ProductCategory[] = [
  'MEDICAL_DEVICE', 'IN_VITRO_DIAGNOSTIC', 'CONTRACEPTIVE_MECHANICAL', 'SURGICAL_DRESSING',
];

const HOMOEO_CATEGORIES: ProductCategory[] = ['HOMOEOPATHIC_MEDICINE'];

const COSMETIC_CATEGORIES: ProductCategory[] = ['PERSONAL_CARE_COSMETIC'];

const ALL_PACKAGED_CATEGORIES: ProductCategory[] = [
  'SEED_AGRICULTURE',
  'FERTILIZER_CHEMICAL',
  'PESTICIDE_CROP_PROTECTION',
  'PERSONAL_CARE_COSMETIC',
  'FOOD_BEVERAGE',
  'HOUSEHOLD_COMMODITY',
  'STATIONERY_OFFICE',
  'APPAREL_TEXTILE',
  'TOYS_CHILDREN',
  'HARDWARE_CONSUMER',
  'PHARMACEUTICAL',
  'ELECTRONICS',
  'GENERAL_PACKAGED_COMMODITY',
  'UNKNOWN',
];

export const STATUTORY_RULES: StatutoryRule[] = [
  // Legal Metrology (Packaged Commodities) Rules 2011 (Applies across ALL pre-packaged commodities)
  {
    ruleId: 'LMPC-R06-1A',
    actName: 'LM_PC_2011',
    sectionRef: 'Rule 6(1)(a)',
    title: 'Product Identity & Common Generic Name',
    description: 'Every package shall bear the generic name of the commodity and product identity on the principal display panel.',
    applicableCategories: ALL_PACKAGED_CATEGORIES,
    isMandatory: true,
    severity: 'CRITICAL',
    effectiveVersion: '2026.1',
    effectiveDate: '2011-04-01',
  },
  {
    ruleId: 'LMPC-R06-1B',
    actName: 'LM_PC_2011',
    sectionRef: 'Rule 6(1)(b) & Sched 2',
    title: 'Net Quantity & Prescribed Tolerance (MPE)',
    description: 'Declaration of net quantity in terms of standard unit of weight/measure and adherence to Maximum Permissible Error limits.',
    applicableCategories: ALL_PACKAGED_CATEGORIES,
    isMandatory: true,
    severity: 'CRITICAL',
    effectiveVersion: '2026.1',
    effectiveDate: '2011-04-01',
  },
  {
    ruleId: 'LMPC-R06-1C',
    actName: 'LM_PC_2011',
    sectionRef: 'Rule 6(1)(c)',
    title: 'Manufacturer / Packer / Importer Name & Complete Address',
    description: 'Name and complete registered address of the manufacturer, or packer, or importer with city and pin code.',
    applicableCategories: ALL_PACKAGED_CATEGORIES,
    isMandatory: true,
    severity: 'CRITICAL',
    effectiveVersion: '2026.1',
    effectiveDate: '2011-04-01',
  },
  {
    ruleId: 'LMPC-R06-1D',
    actName: 'LM_PC_2011',
    sectionRef: 'Rule 6(1)(d) & Rule 6(2)',
    title: 'Maximum Retail Price (MRP) & Unit Sale Price (USP)',
    description: 'MRP in Indian Rupees inclusive of all taxes, clearly legible. For packs >1kg/1L/10N, unit sale price must be declared.',
    applicableCategories: ALL_PACKAGED_CATEGORIES,
    isMandatory: true,
    severity: 'CRITICAL',
    effectiveVersion: '2026.1',
    effectiveDate: '2011-04-01',
  },
  {
    ruleId: 'LMPC-R18-OVERCHARGE',
    actName: 'LM_PC_2011',
    sectionRef: 'Rule 18(2) & LM Act Sec 36',
    title: 'Prohibition of Retail Sale Above Maximum Retail Price (MRP)',
    description: 'No retail dealer, merchant, or e-commerce seller shall sell any packaged commodity at a price exceeding the declared Maximum Retail Price (MRP).',
    applicableCategories: ALL_PACKAGED_CATEGORIES,
    isMandatory: true,
    severity: 'CRITICAL',
    effectiveVersion: '2026.1',
    effectiveDate: '2011-04-01',
    statutoryPenaltyRef: 'LM Act 2009 Section 36(1) Fine up to ₹25,000 for first offence, ₹50,000 / imprisonment for repeat offence',
  },
  {
    ruleId: 'LMPC-R06-1E',
    actName: 'LM_PC_2011',
    sectionRef: 'Rule 6(1)(e)',
    title: 'Month and Year of Manufacture or Packing',
    description: 'Clear statement of the month and year of manufacture, packing, or importation (e.g., "Mfg: 08/2026" or "Pkd: AUG 2026").',
    applicableCategories: ALL_PACKAGED_CATEGORIES,
    isMandatory: true,
    severity: 'MAJOR',
    effectiveVersion: '2026.1',
    effectiveDate: '2011-04-01',
  },
  {
    ruleId: 'LMPC-R06-1N',
    actName: 'LM_PC_2011',
    sectionRef: 'Rule 6(1)(n) & Rule 18',
    title: 'Consumer Care Helpline & Grievance Contact Details',
    description: 'Name, address, telephone helpline number, and email ID of the person/officer who can be contacted for consumer grievances.',
    applicableCategories: ALL_PACKAGED_CATEGORIES,
    isMandatory: true,
    severity: 'CRITICAL',
    effectiveVersion: '2026.1',
    effectiveDate: '2015-05-14',
  },

  // Cosmetics Rules, 2020 (CDSCO / Drugs & Cosmetics Act, 1940)
  {
    ruleId: 'COSM-R34-INGREDIENTS',
    actName: 'COSMETICS_RULES_2020',
    sectionRef: 'Rule 34(1)(b) & Rule 34(3)',
    title: 'Mandatory Ingredient Declaration (INCI List)',
    description: 'Every cosmetic container/package shall carry a full list of ingredients in descending order of weight or concentration.',
    applicableCategories: ['PERSONAL_CARE_COSMETIC'],
    isMandatory: true,
    severity: 'CRITICAL',
    effectiveVersion: '2020.1',
    effectiveDate: '2020-12-15',
  },
  {
    ruleId: 'COSM-R34-MFG-LIC',
    actName: 'COSMETICS_RULES_2020',
    sectionRef: 'Rule 34(1)(a) & CDSCO Form COS-8',
    title: 'Cosmetic Manufacturing License Number',
    description: 'Declaration of valid Manufacturing License Number (e.g. "Mfg Lic No. M-xxx" or "COS-xxx") issued by State Licensing Authority.',
    applicableCategories: ['PERSONAL_CARE_COSMETIC'],
    isMandatory: true,
    severity: 'CRITICAL',
    effectiveVersion: '2020.1',
    effectiveDate: '2020-12-15',
  },
  {
    ruleId: 'COSM-R34-EXPIRY',
    actName: 'COSMETICS_RULES_2020',
    sectionRef: 'Rule 34(1)(e)',
    title: 'Use Before / Expiry Date Statement',
    description: 'Cosmetic packages with shelf life <= 30 months must declare "Use Before / Expiry Date (MM/YY or Month Year)".',
    applicableCategories: ['PERSONAL_CARE_COSMETIC'],
    isMandatory: true,
    severity: 'CRITICAL',
    effectiveVersion: '2020.1',
    effectiveDate: '2020-12-15',
  },
  {
    ruleId: 'COSM-R34-BATCH',
    actName: 'COSMETICS_RULES_2020',
    sectionRef: 'Rule 34(1)(c)',
    title: 'Batch / Lot Reference Code',
    description: 'Every cosmetic package must bear a distinctive Batch Number or Lot Reference code preceded by letter "B" or "Batch No.".',
    applicableCategories: ['PERSONAL_CARE_COSMETIC'],
    isMandatory: true,
    severity: 'MAJOR',
    effectiveVersion: '2020.1',
    effectiveDate: '2020-12-15',
  },

  // FSSAI Food Safety and Standards (Labelling and Display) Regulations 2020
  {
    ruleId: 'FSSAI-R05-LIC',
    actName: 'FSSAI_2020',
    sectionRef: 'FSSAI Reg 5(1) & FSSAI Logo',
    title: 'FSSAI License Number & Logo',
    description: 'Mandatory FSSAI logo and 14-digit Food Safety License Number displayed on the principal display panel.',
    applicableCategories: ['FOOD_BEVERAGE'],
    isMandatory: true,
    severity: 'CRITICAL',
    effectiveVersion: '2020.1',
    effectiveDate: '2020-11-17',
  },
  {
    ruleId: 'FSSAI-R05-VEG',
    actName: 'FSSAI_2020',
    sectionRef: 'FSSAI Reg 5(4)',
    title: 'Veg / Non-Veg Standard Symbol',
    description: 'Green filled circle inside green square for Vegetarian, or Brown triangle inside brown square for Non-Vegetarian food.',
    applicableCategories: ['FOOD_BEVERAGE'],
    isMandatory: true,
    severity: 'CRITICAL',
    effectiveVersion: '2020.1',
    effectiveDate: '2020-11-17',
  },

  // Electronics & Electrical Consumer Products Standards
  {
    ruleId: 'ELEC-BIS-SAFETY',
    actName: 'BIS_COMPULSORY_REGISTRATION',
    sectionRef: 'CRO 2012 / IS 16102',
    title: 'BIS Registration Marking & BEE Energy Label',
    description: 'Mandatory Bureau of Indian Standards (BIS) Registration Logo (R-XXXXXXXX) and BEE Star Energy Rating label where applicable.',
    applicableCategories: ['ELECTRONICS'],
    isMandatory: true,
    severity: 'CRITICAL',
    effectiveVersion: '2026.1',
    effectiveDate: '2012-09-07',
  },

  // Toys (Quality Control) Order & BIS Safety Standards
  {
    ruleId: 'TOYS-BIS-IS9873',
    actName: 'TOYS_QUALITY_CONTROL_ORDER',
    sectionRef: 'IS 9873 Part 1 / Rule 6',
    title: 'BIS Safety Standard Mark & Age Suitability Warning',
    description: 'Mandatory ISI Mark (IS 9873), age suitability warning pictogram, and small parts choking hazard warning on packaging.',
    applicableCategories: ['TOYS_CHILDREN'],
    isMandatory: true,
    severity: 'CRITICAL',
    effectiveVersion: '2021.1',
    effectiveDate: '2021-01-01',
  },

  // Apparel & Textile Products
  {
    ruleId: 'TEX-FIBRE-COMP',
    actName: 'TEXTILE_LABELLING_RULES',
    sectionRef: 'LM(PC) Sched 2 & Textile Order',
    title: 'Fibre Composition & Size Declaration',
    description: 'Mandatory percentage declaration of fibre composition (e.g. 100% Cotton) and international standard garment size (S, M, L, XL).',
    applicableCategories: ['APPAREL_TEXTILE'],
    isMandatory: true,
    severity: 'MAJOR',
    effectiveVersion: '2026.1',
    effectiveDate: '2011-04-01',
  },

  // The Seeds Act 1966 & Seeds Rules 1968 (Applies ONLY to Certified/Notified Agricultural Seeds)
  {
    ruleId: 'SEEDS-SEC06-GERM',
    actName: 'SEEDS_ACT_1966',
    sectionRef: 'Section 6(a) & Rule 7',
    title: 'Minimum Germination Percentage Standard',
    description: 'Every certified/notified seed package must declare minimum germination percentage meeting central seed committee standards (e.g. 85% for Hybrid Maize, Wheat).',
    applicableCategories: ['SEED_AGRICULTURE'],
    isMandatory: true,
    severity: 'CRITICAL',
    effectiveVersion: '2026.1',
    effectiveDate: '1968-10-02',
  },
  {
    ruleId: 'SEEDS-SEC06-PURITY',
    actName: 'SEEDS_ACT_1966',
    sectionRef: 'Section 6(a) & Rule 8',
    title: 'Minimum Genetic & Physical Purity Percentage',
    description: 'Declaration of minimum physical and genetic purity (standards require 98.0% or 99.0% depending on seed crop).',
    applicableCategories: ['SEED_AGRICULTURE'],
    isMandatory: true,
    severity: 'MAJOR',
    effectiveVersion: '2026.1',
    effectiveDate: '1968-10-02',
  },
  {
    ruleId: 'SEEDS-RULE10-VALIDITY',
    actName: 'SEEDS_ACT_1966',
    sectionRef: 'Section 7 & Rule 10',
    title: 'Seed Lot Number & 9-Month Test Validity Period',
    description: 'Batch/Lot identification number, certified seed class tag, and test certificate date with standard 9-month field validity.',
    applicableCategories: ['SEED_AGRICULTURE'],
    isMandatory: true,
    severity: 'CRITICAL',
    effectiveVersion: '2026.1',
    effectiveDate: '1968-10-02',
  },

  // Fertilizer Control Order (FCO) 1985 (Applies ONLY to Chemical & Bio-Fertilizers)
  {
    ruleId: 'FCO-SCHED01-NUTRIENTS',
    actName: 'FCO_1985',
    sectionRef: 'Clause 19 & Sched 1 Part A',
    title: 'Guaranteed Nutrient Ratio & Chemical Grade Specification',
    description: 'Declared composition of primary and secondary plant nutrients matching statutory Fertilizer Control Order limits (e.g. 19:19:19).',
    applicableCategories: ['FERTILIZER_CHEMICAL'],
    isMandatory: true,
    severity: 'CRITICAL',
    effectiveVersion: '2026.1',
    effectiveDate: '1985-09-25',
  },
  {
    ruleId: 'FCO-CLAUSE21-BIS',
    actName: 'FCO_1985',
    sectionRef: 'Clause 21 & ISI Mark',
    title: 'Mandatory BIS / ISI Certification Mark & FCO License',
    description: 'Package must display statutory fertilizer manufacturer license and Bureau of Indian Standards (ISI) verification mark.',
    applicableCategories: ['FERTILIZER_CHEMICAL'],
    isMandatory: true,
    severity: 'MAJOR',
    effectiveVersion: '2026.1',
    effectiveDate: '1985-09-25',
  },

  // Insecticides Act 1968 / Insecticides Rules 1971 (Pesticides / Crop Protection)
  {
    ruleId: 'PEST-SEC09-CIB',
    actName: 'INSECTICIDES_ACT_1968',
    sectionRef: 'Section 9 & Rule 19',
    title: 'CIB&RC Registration Number & License',
    description: 'Mandatory registration number issued by Central Insecticides Board & Registration Committee (CIB&RC) and state manufacturing license.',
    applicableCategories: ['PESTICIDE_CROP_PROTECTION'],
    isMandatory: true,
    severity: 'CRITICAL',
    effectiveVersion: '2026.1',
    effectiveDate: '1971-10-30',
  },
  {
    ruleId: 'PEST-RULE19-ANTIDOTE',
    actName: 'INSECTICIDES_ACT_1968',
    sectionRef: 'Rule 19(1) & Toxicity Warning',
    title: 'Antidote Statement & Toxicity Diamond Symbol',
    description: 'Mandatory warning text "POISON / DANGER", prescribed toxicity diamond color code, and emergency medical antidote statement.',
    applicableCategories: ['PESTICIDE_CROP_PROTECTION'],
    isMandatory: true,
    severity: 'CRITICAL',
    effectiveVersion: '2026.1',
    effectiveDate: '1971-10-30',
  },

  // Imported Commodity Rules
  {
    ruleId: 'IMPORT-COO-01',
    actName: 'IMPORTED_RULES',
    sectionRef: 'LM(PC) Rule 6(10) & Customs S.46',
    title: 'Country of Origin & Foreign Manufacturer Declaration',
    description: 'Every imported commodity must explicitly declare Country of Origin ("Made in / Country of Origin: X") and name of foreign packer.',
    applicableCategories: ALL_PACKAGED_CATEGORIES,
    isMandatory: true,
    severity: 'CRITICAL',
    effectiveVersion: '2026.1',
    effectiveDate: '2020-01-01',
  },
  {
    ruleId: 'IMPORT-REG-02',
    actName: 'IMPORTED_RULES',
    sectionRef: 'LM(PC) Rule 27',
    title: 'Importer Registration Certificate & Local Address in India',
    description: 'Mandatory declaration of Indian importer registration number, corporate office address, and import clearance reference.',
    applicableCategories: ALL_PACKAGED_CATEGORIES,
    isMandatory: true,
    severity: 'CRITICAL',
    effectiveVersion: '2026.1',
    effectiveDate: '2020-01-01',
  },

  // ═══════════════════════════════════════════════════════════════════════════
  // MODULE A — GENERAL DRUG LABELLING (D&C Rules 1945, Rule 95 & 96)
  // ═══════════════════════════════════════════════════════════════════════════
  {
    ruleId: 'DCR-R96-PROPERNAME',
    actName: 'DRUGS_COSMETICS_RULES_1945',
    sectionRef: 'Rule 96(1)(a)',
    title: 'Drug Proper Name / Generic Name',
    description: 'The proper name (approved generic or pharmacopoeial name) of the drug must appear on the label, appropriately displayed relative to the trade/brand name.',
    applicableCategories: ALL_DRUG_CATEGORIES,
    isMandatory: true,
    severity: 'CRITICAL',
    effectiveVersion: '2026.1',
    effectiveDate: '1945-10-01',
    statutoryPenaltyRef: 'D&C Act Section 18(a)(i) / Section 27',
  },
  {
    ruleId: 'DCR-R96-NETCONTENT',
    actName: 'DRUGS_COSMETICS_RULES_1945',
    sectionRef: 'Rule 96(1)(d)',
    title: 'Drug Net Content in Metric Units',
    description: 'Net content of the drug must be declared in appropriate metric units. Active ingredient declaration must be in the appropriate form for the dosage type (e.g., mg/tablet, mg/5ml, % w/w for topicals).',
    applicableCategories: ALL_DRUG_CATEGORIES,
    isMandatory: true,
    severity: 'CRITICAL',
    effectiveVersion: '2026.1',
    effectiveDate: '1945-10-01',
  },
  {
    ruleId: 'DCR-R96-ACTIVEING',
    actName: 'DRUGS_COSMETICS_RULES_1945',
    sectionRef: 'Rule 96(1)(e)',
    title: 'Active Ingredient Declaration',
    description: 'Active ingredient(s) with quantity per dosage unit must be clearly declared. For compound preparations, all active ingredients with amounts must be listed.',
    applicableCategories: ALL_DRUG_CATEGORIES,
    isMandatory: true,
    severity: 'CRITICAL',
    effectiveVersion: '2026.1',
    effectiveDate: '1945-10-01',
  },
  {
    ruleId: 'DCR-R96-MFGNAME',
    actName: 'DRUGS_COSMETICS_RULES_1945',
    sectionRef: 'Rule 96(1)(f)',
    title: 'Drug Manufacturer Name & Address',
    description: 'Name and complete address of the manufacturer must be declared on the label.',
    applicableCategories: ALL_DRUG_CATEGORIES,
    isMandatory: true,
    severity: 'CRITICAL',
    effectiveVersion: '2026.1',
    effectiveDate: '1945-10-01',
  },
  {
    ruleId: 'DCR-R96-BATCHNO',
    actName: 'DRUGS_COSMETICS_RULES_1945',
    sectionRef: 'Rule 96(1)(g)',
    title: 'Drug Batch / Lot Number',
    description: 'Distinctive Batch Number (or Lot Number) preceded by "B No." or "Batch No." must be declared on every drug label.',
    applicableCategories: ALL_DRUG_CATEGORIES,
    isMandatory: true,
    severity: 'CRITICAL',
    effectiveVersion: '2026.1',
    effectiveDate: '1945-10-01',
  },
  {
    ruleId: 'DCR-R96-MFGLICNO',
    actName: 'DRUGS_COSMETICS_RULES_1945',
    sectionRef: 'Rule 96(1)(h)',
    title: 'Drug Manufacturing Licence Number',
    description: 'Manufacturing Licence Number issued by the State/Central Licensing Authority must be declared on the label.',
    applicableCategories: ALL_DRUG_CATEGORIES,
    isMandatory: true,
    severity: 'CRITICAL',
    effectiveVersion: '2026.1',
    effectiveDate: '1945-10-01',
  },
  {
    ruleId: 'DCR-R96-MFGDATE',
    actName: 'DRUGS_COSMETICS_RULES_1945',
    sectionRef: 'Rule 96(1)(i)',
    title: 'Drug Date of Manufacture',
    description: 'Date of manufacture (month and year) must be declared on the label where required by the applicable schedule.',
    applicableCategories: ALL_DRUG_CATEGORIES,
    isMandatory: true,
    severity: 'MAJOR',
    effectiveVersion: '2026.1',
    effectiveDate: '1945-10-01',
  },
  {
    ruleId: 'DCR-R96-EXPIRY',
    actName: 'DRUGS_COSMETICS_RULES_1945',
    sectionRef: 'Rule 96(1)(j) & Schedule P',
    title: 'Drug Expiry / Best Before Date',
    description: 'Date of expiry (or "Use before" date) must be declared. For Schedule P drugs the shelf life must not exceed the applicable period. Expiry must be expressed as month and year at minimum.',
    applicableCategories: ALL_DRUG_CATEGORIES,
    isMandatory: true,
    severity: 'CRITICAL',
    effectiveVersion: '2026.1',
    effectiveDate: '1945-10-01',
    statutoryPenaltyRef: 'D&C Act Section 27(b)',
  },
  {
    ruleId: 'DCR-R96-REDLINE',
    actName: 'DRUGS_COSMETICS_RULES_1945',
    sectionRef: 'Rule 96(2)',
    title: 'Red Vertical Line (Caution Drugs)',
    description: 'A conspicuous red vertical line must appear on the left side of the label for drugs that require a caution but are not covered by Schedule H/H1/X.',
    applicableCategories: ['DRUG_GENERAL', 'PHARMACEUTICAL'],
    isMandatory: false,
    severity: 'MODERATE',
    effectiveVersion: '2026.1',
    effectiveDate: '1945-10-01',
  },
  {
    ruleId: 'DCR-R96-EXTERNALUSE',
    actName: 'DRUGS_COSMETICS_RULES_1945',
    sectionRef: 'Rule 96(3)',
    title: '"FOR EXTERNAL USE ONLY" Declaration',
    description: 'Any medicine intended for external application only (lotion, liniment, ointment, antiseptic cream, external liquid, etc.) must prominently bear the words "FOR EXTERNAL USE ONLY".',
    applicableCategories: ALL_DRUG_CATEGORIES,
    isMandatory: false,
    severity: 'CRITICAL',
    effectiveVersion: '2026.1',
    effectiveDate: '1945-10-01',
  },
  {
    ruleId: 'DCR-R96-ALCOHOL',
    actName: 'DRUGS_COSMETICS_RULES_1945',
    sectionRef: 'Rule 96(1)(l)',
    title: 'Alcohol Percentage Declaration',
    description: 'Where a drug contains alcohol, the percentage of alcohol by volume must be declared on the label.',
    applicableCategories: ALL_DRUG_CATEGORIES,
    isMandatory: false,
    severity: 'MAJOR',
    effectiveVersion: '2026.1',
    effectiveDate: '1945-10-01',
  },
  {
    ruleId: 'DCR-R96-PHYSICIANSAMPLE',
    actName: 'DRUGS_COSMETICS_RULES_1945',
    sectionRef: 'Rule 96(1)(m)',
    title: 'Physician Sample — Not for Sale Marking',
    description: 'Free medical samples must bear the words "Physician\'s Sample — Not to be sold" in a conspicuous manner.',
    applicableCategories: ALL_DRUG_CATEGORIES,
    isMandatory: false,
    severity: 'CRITICAL',
    effectiveVersion: '2026.1',
    effectiveDate: '1945-10-01',
  },
  {
    ruleId: 'DCR-R96-IMPORT-LICENCE',
    actName: 'DRUGS_COSMETICS_RULES_1945',
    sectionRef: 'Rule 96(1)(k)',
    title: 'Imported Drug — Import Licence Number',
    description: 'For imported drugs, the import licence number and the name and address of the importer in India must be declared on the label.',
    applicableCategories: ALL_DRUG_CATEGORIES,
    isMandatory: false,
    severity: 'CRITICAL',
    effectiveVersion: '2026.1',
    effectiveDate: '1945-10-01',
  },

  // ═══════════════════════════════════════════════════════════════════════════
  // MODULE B — SCHEDULE G (D&C Rules 1945, Rule 97)
  // ═══════════════════════════════════════════════════════════════════════════
  {
    ruleId: 'DCR-SCHG-CAUTION',
    actName: 'DRUGS_COSMETICS_RULES_1945',
    sectionRef: 'Rule 97 & Schedule G',
    title: 'Schedule G Cautionary Statement',
    description: 'Every drug containing a Schedule G substance must display the required cautionary statement: "Caution: It is dangerous to take this preparation except under medical supervision." This must appear on both inner and outer labels in a conspicuous manner.',
    applicableCategories: SCHEDULE_G_CATEGORIES,
    isMandatory: true,
    severity: 'CRITICAL',
    effectiveVersion: '2026.1',
    effectiveDate: '1945-10-01',
    statutoryPenaltyRef: 'D&C Act Section 27',
  },

  // ═══════════════════════════════════════════════════════════════════════════
  // MODULE C — SCHEDULE H (D&C Rules 1945, Rule 65 & Second Schedule Part H)
  // ═══════════════════════════════════════════════════════════════════════════
  {
    ruleId: 'DCR-SCHH-RX',
    actName: 'DRUGS_COSMETICS_RULES_1945',
    sectionRef: 'Rule 65(2) & Schedule H',
    title: 'Schedule H — Rx Symbol (Prescription Only)',
    description: 'Drugs containing Schedule H substances must bear the symbol "Rx" in a conspicuous and legible manner on the left top corner of the label. The symbol must be clearly visible and appropriately prominent — not merely hidden in fine print.',
    applicableCategories: SCHEDULE_H_CATEGORIES,
    isMandatory: true,
    severity: 'CRITICAL',
    effectiveVersion: '2026.1',
    effectiveDate: '1945-10-01',
    statutoryPenaltyRef: 'D&C Act Section 27',
  },
  {
    ruleId: 'DCR-SCHH-WARNING',
    actName: 'DRUGS_COSMETICS_RULES_1945',
    sectionRef: 'Rule 65(2) & Schedule H',
    title: 'Schedule H — Mandatory Warning Text',
    description: 'The Schedule H warning "Schedule H Drug — Warning: To be sold by retail on the prescription of a Registered Medical Practitioner only" must appear on the label.',
    applicableCategories: SCHEDULE_H_CATEGORIES,
    isMandatory: true,
    severity: 'CRITICAL',
    effectiveVersion: '2026.1',
    effectiveDate: '1945-10-01',
  },

  // ═══════════════════════════════════════════════════════════════════════════
  // MODULE D — SCHEDULE H1 (D&C Rules 1945, Rule 65A)
  // ═══════════════════════════════════════════════════════════════════════════
  {
    ruleId: 'DCR-SCHH1-RED-RX',
    actName: 'DRUGS_COSMETICS_RULES_1945',
    sectionRef: 'Rule 65A(2)(a)',
    title: 'Schedule H1 — Red Rx Symbol at Left Top Corner',
    description: 'Drugs containing Schedule H1 substances must bear the symbol "Rx" printed in RED at the left top corner of the label in a conspicuous manner.',
    applicableCategories: SCHEDULE_H1_CATEGORIES,
    isMandatory: true,
    severity: 'CRITICAL',
    effectiveVersion: '2026.1',
    effectiveDate: '1945-10-01',
    statutoryPenaltyRef: 'D&C Act Section 27',
  },
  {
    ruleId: 'DCR-SCHH1-WARNINGBOX',
    actName: 'DRUGS_COSMETICS_RULES_1945',
    sectionRef: 'Rule 65A(2)(b)',
    title: 'Schedule H1 — Warning Box with Red Border',
    description: 'A warning box with a conspicuous red border must appear on the label of every Schedule H1 drug. This box must be clearly distinct and not merged with regular label text.',
    applicableCategories: SCHEDULE_H1_CATEGORIES,
    isMandatory: true,
    severity: 'CRITICAL',
    effectiveVersion: '2026.1',
    effectiveDate: '1945-10-01',
  },
  {
    ruleId: 'DCR-SCHH1-WARNING-TEXT',
    actName: 'DRUGS_COSMETICS_RULES_1945',
    sectionRef: 'Rule 65A(2)(c) & Schedule H1',
    title: 'Schedule H1 — Warning Language & Prescription Statement',
    description: 'The Schedule H1 warning "Schedule H1 Drug — Warning: It is dangerous to take this preparation except under medical supervision. Not to be sold by retail except on the prescription of a Specialist." must appear within the red-bordered warning box.',
    applicableCategories: SCHEDULE_H1_CATEGORIES,
    isMandatory: true,
    severity: 'CRITICAL',
    effectiveVersion: '2026.1',
    effectiveDate: '1945-10-01',
  },

  // ═══════════════════════════════════════════════════════════════════════════
  // MODULE E — SCHEDULE X (D&C Rules 1945, Rule 97A)
  // ═══════════════════════════════════════════════════════════════════════════
  {
    ruleId: 'DCR-SCHX-XRXSYMBOL',
    actName: 'DRUGS_COSMETICS_RULES_1945',
    sectionRef: 'Rule 97A(2)(a) & Schedule X',
    title: 'Schedule X — XRx Symbol in Red',
    description: 'Drugs containing Schedule X substances must bear the symbol "XRx" printed in RED in a conspicuous manner on the label.',
    applicableCategories: SCHEDULE_X_CATEGORIES,
    isMandatory: true,
    severity: 'CRITICAL',
    effectiveVersion: '2026.1',
    effectiveDate: '1945-10-01',
    statutoryPenaltyRef: 'D&C Act Section 27',
  },
  {
    ruleId: 'DCR-SCHX-WARNING',
    actName: 'DRUGS_COSMETICS_RULES_1945',
    sectionRef: 'Rule 97A(2)(c) & Schedule X',
    title: 'Schedule X — Warning & Prescription Statement',
    description: 'The Schedule X warning "Schedule X Drug — Warning: To be sold by retail on the prescription of a Registered Medical Practitioner only and the prescription to be retained by the pharmacist" must appear on the label.',
    applicableCategories: SCHEDULE_X_CATEGORIES,
    isMandatory: true,
    severity: 'CRITICAL',
    effectiveVersion: '2026.1',
    effectiveDate: '1945-10-01',
  },
  {
    ruleId: 'DCR-SCHX-PACKSIZE-TAB',
    actName: 'DRUGS_COSMETICS_RULES_1945',
    sectionRef: 'Rule 97A(3)(a) & Schedule X',
    title: 'Schedule X — Maximum Package Size (Tablets/Capsules)',
    description: 'Tablets or capsules containing Schedule X substances must not be packed/sold in quantities exceeding 100 unit doses (tablets or capsules) per package.',
    applicableCategories: SCHEDULE_X_CATEGORIES,
    isMandatory: true,
    severity: 'CRITICAL',
    effectiveVersion: '2026.1',
    effectiveDate: '1945-10-01',
  },
  {
    ruleId: 'DCR-SCHX-PACKSIZE-LIQ',
    actName: 'DRUGS_COSMETICS_RULES_1945',
    sectionRef: 'Rule 97A(3)(b) & Schedule X',
    title: 'Schedule X — Maximum Package Size (Oral Liquid)',
    description: 'Oral liquid preparations containing Schedule X substances must not be packed/sold in containers exceeding 300 ml per package.',
    applicableCategories: SCHEDULE_X_CATEGORIES,
    isMandatory: true,
    severity: 'CRITICAL',
    effectiveVersion: '2026.1',
    effectiveDate: '1945-10-01',
  },
  {
    ruleId: 'DCR-SCHX-PACKSIZE-INJ',
    actName: 'DRUGS_COSMETICS_RULES_1945',
    sectionRef: 'Rule 97A(3)(c) & Schedule X',
    title: 'Schedule X — Maximum Package Size (Injections)',
    description: 'Injections containing Schedule X substances must not exceed 5 ml per individual container/ampoule.',
    applicableCategories: SCHEDULE_X_CATEGORIES,
    isMandatory: true,
    severity: 'CRITICAL',
    effectiveVersion: '2026.1',
    effectiveDate: '1945-10-01',
  },

  // ═══════════════════════════════════════════════════════════════════════════
  // MODULE F — FALSE/PROHIBITED DRUG CLAIMS (D&C Act Schedule J)
  // ═══════════════════════════════════════════════════════════════════════════
  {
    ruleId: 'DCR-SCHJ-PROHIBITED-CLAIM',
    actName: 'DRUGS_COSMETICS_ACT_1940',
    sectionRef: 'Section 33(3) & Schedule J',
    title: 'Prohibited Therapeutic / Disease Claim',
    description: 'A drug label must not make any claim (express or implied) to prevent, cure, mitigate, or treat any disease listed in Schedule J, or make any false, misleading, or exaggerated claim of therapeutic superiority. Detected claims must be evaluated for prohibited category.',
    applicableCategories: ALL_DRUG_CATEGORIES,
    isMandatory: true,
    severity: 'CRITICAL',
    effectiveVersion: '2026.1',
    effectiveDate: '1940-04-10',
    statutoryPenaltyRef: 'D&C Act Section 27(d)',
  },

  // ═══════════════════════════════════════════════════════════════════════════
  // MODULE G — VETERINARY DRUGS
  // ═══════════════════════════════════════════════════════════════════════════
  {
    ruleId: 'DCR-VET-WITHDRAWAL',
    actName: 'DRUGS_COSMETICS_RULES_1945',
    sectionRef: 'Rule 96-A & Schedule V',
    title: 'Veterinary Drug — Withdrawal Period Declaration',
    description: 'For medicines intended for food-producing animals, the applicable withdrawal period (number of days before slaughter / milking) must be stated on the label. If no withdrawal period applies, "No withdrawal period required" must be stated.',
    applicableCategories: VETERINARY_CATEGORIES,
    isMandatory: true,
    severity: 'CRITICAL',
    effectiveVersion: '2026.1',
    effectiveDate: '1945-10-01',
  },

  // ═══════════════════════════════════════════════════════════════════════════
  // MODULE H — BIOLOGICAL / SCHEDULE C PRODUCTS (D&C Rules)
  // ═══════════════════════════════════════════════════════════════════════════
  {
    ruleId: 'DCR-SCHC-POTENCY',
    actName: 'DRUGS_COSMETICS_RULES_1945',
    sectionRef: 'Rule 96(1) & Schedule C',
    title: 'Biological / Schedule C — Potency Declaration',
    description: 'Biological and special products (Schedule C/C1) must declare potency where applicable. Potency must be expressed in standard pharmacopoeial units.',
    applicableCategories: BIOLOGICAL_CATEGORIES,
    isMandatory: true,
    severity: 'CRITICAL',
    effectiveVersion: '2026.1',
    effectiveDate: '1945-10-01',
  },
  {
    ruleId: 'DCR-SCHC-IMPORT-LICENCE',
    actName: 'DRUGS_COSMETICS_RULES_1945',
    sectionRef: 'Rule 96(1)(k) & Schedule C',
    title: 'Biological / Schedule C — Import Licence (Imported Products)',
    description: 'Imported biological / Schedule C products must declare the import licence number and the name and address of the Indian importer on the label.',
    applicableCategories: BIOLOGICAL_CATEGORIES,
    isMandatory: false,
    severity: 'CRITICAL',
    effectiveVersion: '2026.1',
    effectiveDate: '1945-10-01',
  },
  {
    ruleId: 'DCR-SCHC-STORAGE',
    actName: 'DRUGS_COSMETICS_RULES_1945',
    sectionRef: 'Rule 96 & Schedule F',
    title: 'Biological / Special Product — Storage & Handling Precautions',
    description: 'Biological / special products must declare applicable storage conditions (e.g., "Store between 2°C and 8°C"), handling precautions, and any cold-chain requirements on the label.',
    applicableCategories: BIOLOGICAL_CATEGORIES,
    isMandatory: true,
    severity: 'MAJOR',
    effectiveVersion: '2026.1',
    effectiveDate: '1945-10-01',
  },

  // ═══════════════════════════════════════════════════════════════════════════
  // MODULE I — MEDICAL DEVICES (Medical Devices Rules 2017, Rule 109-A)
  // ═══════════════════════════════════════════════════════════════════════════
  {
    ruleId: 'MDR-109A-PROPNAME',
    actName: 'MEDICAL_DEVICES_RULES_2017',
    sectionRef: 'Rule 109-A(1)(a)',
    title: 'Medical Device — Proper Name',
    description: 'The proper name of the medical device necessary to identify it must appear on the label.',
    applicableCategories: MEDICAL_DEVICE_CATEGORIES,
    isMandatory: true,
    severity: 'CRITICAL',
    effectiveVersion: '2026.1',
    effectiveDate: '2017-01-31',
    statutoryPenaltyRef: 'MDR 2017 Rule 109-A',
  },
  {
    ruleId: 'MDR-109A-MFGNAME',
    actName: 'MEDICAL_DEVICES_RULES_2017',
    sectionRef: 'Rule 109-A(1)(c)',
    title: 'Medical Device — Manufacturer Name',
    description: 'Name of the manufacturer of the medical device must be declared on the label.',
    applicableCategories: MEDICAL_DEVICE_CATEGORIES,
    isMandatory: true,
    severity: 'CRITICAL',
    effectiveVersion: '2026.1',
    effectiveDate: '2017-01-31',
  },
  {
    ruleId: 'MDR-109A-MFGADDR',
    actName: 'MEDICAL_DEVICES_RULES_2017',
    sectionRef: 'Rule 109-A(1)(d)',
    title: 'Medical Device — Manufacturing Premises Address',
    description: 'The address of the manufacturing premises of the medical device must be declared on the label.',
    applicableCategories: MEDICAL_DEVICE_CATEGORIES,
    isMandatory: true,
    severity: 'CRITICAL',
    effectiveVersion: '2026.1',
    effectiveDate: '2017-01-31',
  },
  {
    ruleId: 'MDR-109A-NETQTY',
    actName: 'MEDICAL_DEVICES_RULES_2017',
    sectionRef: 'Rule 109-A(1)(e)',
    title: 'Medical Device — Net Quantity in Metric System',
    description: 'Net quantity of the device must be declared in the metric system where applicable.',
    applicableCategories: MEDICAL_DEVICE_CATEGORIES,
    isMandatory: true,
    severity: 'MAJOR',
    effectiveVersion: '2026.1',
    effectiveDate: '2017-01-31',
  },
  {
    ruleId: 'MDR-109A-MFGDATE',
    actName: 'MEDICAL_DEVICES_RULES_2017',
    sectionRef: 'Rule 109-A(1)(f)',
    title: 'Medical Device — Date of Manufacture',
    description: 'Date of manufacture of the medical device must be declared on the label.',
    applicableCategories: MEDICAL_DEVICE_CATEGORIES,
    isMandatory: true,
    severity: 'MAJOR',
    effectiveVersion: '2026.1',
    effectiveDate: '2017-01-31',
  },
  {
    ruleId: 'MDR-109A-EXPIRY',
    actName: 'MEDICAL_DEVICES_RULES_2017',
    sectionRef: 'Rule 109-A(1)(g)',
    title: 'Medical Device — Date of Expiry / Shelf Life Statement',
    description: 'Date of expiry or a statement of shelf life must be declared on the label. This is mandatory for all applicable medical devices.',
    applicableCategories: MEDICAL_DEVICE_CATEGORIES,
    isMandatory: true,
    severity: 'CRITICAL',
    effectiveVersion: '2026.1',
    effectiveDate: '2017-01-31',
  },
  {
    ruleId: 'MDR-109A-BATCHNO',
    actName: 'MEDICAL_DEVICES_RULES_2017',
    sectionRef: 'Rule 109-A(1)(i)',
    title: 'Medical Device — Batch / Lot Number',
    description: 'A distinctive Batch Number or Lot Number must be declared on the label of every medical device.',
    applicableCategories: MEDICAL_DEVICE_CATEGORIES,
    isMandatory: true,
    severity: 'CRITICAL',
    effectiveVersion: '2026.1',
    effectiveDate: '2017-01-31',
  },
  {
    ruleId: 'MDR-109A-STORAGE',
    actName: 'MEDICAL_DEVICES_RULES_2017',
    sectionRef: 'Rule 109-A(1)(j)',
    title: 'Medical Device — Special Storage / Handling Conditions',
    description: 'Where special storage or handling conditions apply to the medical device, these must be declared on the label (e.g., "Store in a cool dry place", "Do not freeze").',
    applicableCategories: MEDICAL_DEVICE_CATEGORIES,
    isMandatory: false,
    severity: 'MAJOR',
    effectiveVersion: '2026.1',
    effectiveDate: '2017-01-31',
  },
  {
    ruleId: 'MDR-109A-STERILE',
    actName: 'MEDICAL_DEVICES_RULES_2017',
    sectionRef: 'Rule 109-A(1)(k)',
    title: 'Medical Device — Sterile State Indication',
    description: 'If the medical device is supplied in a sterile condition, the word "STERILE" or equivalent must appear on the label.',
    applicableCategories: MEDICAL_DEVICE_CATEGORIES,
    isMandatory: false,
    severity: 'CRITICAL',
    effectiveVersion: '2026.1',
    effectiveDate: '2017-01-31',
  },
  {
    ruleId: 'MDR-109A-STERILMETHOD',
    actName: 'MEDICAL_DEVICES_RULES_2017',
    sectionRef: 'Rule 109-A(1)(l)',
    title: 'Medical Device — Sterilisation Method',
    description: 'Where applicable, the method of sterilisation (e.g., ETO, Gamma radiation, Steam) must be indicated on the label of sterile medical devices.',
    applicableCategories: MEDICAL_DEVICE_CATEGORIES,
    isMandatory: false,
    severity: 'MAJOR',
    effectiveVersion: '2026.1',
    effectiveDate: '2017-01-31',
  },
  {
    ruleId: 'MDR-109A-SINGLEUSE',
    actName: 'MEDICAL_DEVICES_RULES_2017',
    sectionRef: 'Rule 109-A(1)(m)',
    title: 'Medical Device — Single Use Indication',
    description: 'Where a medical device is intended for single use only, the label must clearly indicate this (e.g., "Single Use Only", "Do Not Reuse", or the applicable single-use symbol).',
    applicableCategories: MEDICAL_DEVICE_CATEGORIES,
    isMandatory: false,
    severity: 'CRITICAL',
    effectiveVersion: '2026.1',
    effectiveDate: '2017-01-31',
  },
  {
    ruleId: 'MDR-109A-CLINTRAIL',
    actName: 'MEDICAL_DEVICES_RULES_2017',
    sectionRef: 'Rule 109-A(1)(n)',
    title: 'Medical Device — Clinical Investigation Marking',
    description: 'If the medical device is intended for clinical investigation only, the label must bear the words "FOR CLINICAL INVESTIGATION ONLY" in a conspicuous manner.',
    applicableCategories: MEDICAL_DEVICE_CATEGORIES,
    isMandatory: false,
    severity: 'CRITICAL',
    effectiveVersion: '2026.1',
    effectiveDate: '2017-01-31',
  },
  {
    ruleId: 'MDR-109A-MFGLICNO',
    actName: 'MEDICAL_DEVICES_RULES_2017',
    sectionRef: 'Rule 109-A(1)(q)',
    title: 'Medical Device — Manufacturing Licence Number',
    description: 'For domestically manufactured medical devices, the manufacturing licence number issued by the licensing authority must be declared on the label.',
    applicableCategories: MEDICAL_DEVICE_CATEGORIES,
    isMandatory: true,
    severity: 'CRITICAL',
    effectiveVersion: '2026.1',
    effectiveDate: '2017-01-31',
  },
  {
    ruleId: 'MDR-109A-IMPORT-LIC',
    actName: 'MEDICAL_DEVICES_RULES_2017',
    sectionRef: 'Rule 109-A(1)(s)',
    title: 'Medical Device — Import Licence Number (Imported Devices)',
    description: 'For imported medical devices, the import licence number and the name and address of the Indian importer must be declared on the label.',
    applicableCategories: MEDICAL_DEVICE_CATEGORIES,
    isMandatory: false,
    severity: 'CRITICAL',
    effectiveVersion: '2026.1',
    effectiveDate: '2017-01-31',
  },
  {
    ruleId: 'MDR-109C-SHELFLIFE',
    actName: 'MEDICAL_DEVICES_RULES_2017',
    sectionRef: 'Rule 109-C',
    title: 'Medical Device — Maximum Shelf Life (60 Months)',
    description: 'The shelf life of a medical device must not exceed 60 months from the date of manufacture unless the licensing authority grants an extension with satisfactory justification. Declared expiry must be validated against manufacturing date.',
    applicableCategories: MEDICAL_DEVICE_CATEGORIES,
    isMandatory: true,
    severity: 'MAJOR',
    effectiveVersion: '2026.1',
    effectiveDate: '2017-01-31',
  },

  // ═══════════════════════════════════════════════════════════════════════════
  // MODULE J — HOMOEOPATHIC MEDICINES (D&C Rules 1945, Rule 106-A & 106-B)
  // ═══════════════════════════════════════════════════════════════════════════
  {
    ruleId: 'DCR-R106A-HOMOLABEL',
    actName: 'DRUGS_COSMETICS_RULES_1945',
    sectionRef: 'Rule 106-A(1)(a)',
    title: 'Homoeopathic Medicine — Mandatory Category Declaration',
    description: 'The words "Homoeopathic medicine" must appear on the label of every homoeopathic product.',
    applicableCategories: HOMOEO_CATEGORIES,
    isMandatory: true,
    severity: 'CRITICAL',
    effectiveVersion: '2026.1',
    effectiveDate: '1945-10-01',
  },
  {
    ruleId: 'DCR-R106A-MEDNAME',
    actName: 'DRUGS_COSMETICS_RULES_1945',
    sectionRef: 'Rule 106-A(1)(b)',
    title: 'Homoeopathic Medicine — Name of Medicine',
    description: 'The name of the homoeopathic medicine including its appropriate pharmacopoeial or descriptive name must be declared on the label.',
    applicableCategories: HOMOEO_CATEGORIES,
    isMandatory: true,
    severity: 'CRITICAL',
    effectiveVersion: '2026.1',
    effectiveDate: '1945-10-01',
  },
  {
    ruleId: 'DCR-R106A-POTENCY',
    actName: 'DRUGS_COSMETICS_RULES_1945',
    sectionRef: 'Rule 106-A(1)(c)',
    title: 'Homoeopathic Medicine — Potency Declaration',
    description: 'Potency of the homoeopathic medicine must be expressed in the appropriate decimal (X), centesimal (C), or millisimal (M/LM) scale.',
    applicableCategories: HOMOEO_CATEGORIES,
    isMandatory: true,
    severity: 'CRITICAL',
    effectiveVersion: '2026.1',
    effectiveDate: '1945-10-01',
  },
  {
    ruleId: 'DCR-R106A-MULTIINGRED',
    actName: 'DRUGS_COSMETICS_RULES_1945',
    sectionRef: 'Rule 106-A(1)(d)',
    title: 'Homoeopathic — Multi-ingredient: Each Ingredient, Potency & Proportion',
    description: 'For multi-ingredient homoeopathic preparations, each ingredient must be listed with its potency and proportion expressed in the metric system.',
    applicableCategories: HOMOEO_CATEGORIES,
    isMandatory: false,
    severity: 'MAJOR',
    effectiveVersion: '2026.1',
    effectiveDate: '1945-10-01',
  },
  {
    ruleId: 'DCR-R106A-MFGADDR',
    actName: 'DRUGS_COSMETICS_RULES_1945',
    sectionRef: 'Rule 106-A(1)(e)',
    title: 'Homoeopathic Medicine — Manufacturer Name & Address',
    description: 'Name and address of the manufacturer or seller (when sold in a non-manufacturer container) must be declared on the label.',
    applicableCategories: HOMOEO_CATEGORIES,
    isMandatory: true,
    severity: 'CRITICAL',
    effectiveVersion: '2026.1',
    effectiveDate: '1945-10-01',
  },
  {
    ruleId: 'DCR-R106A-ALCOHOL',
    actName: 'DRUGS_COSMETICS_RULES_1945',
    sectionRef: 'Rule 106-A(1)(f)',
    title: 'Homoeopathic Medicine — Alcohol Content Declaration',
    description: 'Where the homoeopathic preparation contains alcohol, the percentage of alcohol by volume must be declared on the label.',
    applicableCategories: HOMOEO_CATEGORIES,
    isMandatory: false,
    severity: 'MAJOR',
    effectiveVersion: '2026.1',
    effectiveDate: '1945-10-01',
  },
  {
    ruleId: 'DCR-R106A-MTBATCH',
    actName: 'DRUGS_COSMETICS_RULES_1945',
    sectionRef: 'Rule 106-A(1)(g)',
    title: 'Homoeopathic Mother Tincture — Batch Number',
    description: 'For products using or derived from a mother tincture, the batch number of the mother tincture used in preparation must be declared on the label.',
    applicableCategories: HOMOEO_CATEGORIES,
    isMandatory: false,
    severity: 'MAJOR',
    effectiveVersion: '2026.1',
    effectiveDate: '1945-10-01',
  },
  {
    ruleId: 'DCR-R106A-MTLICNO',
    actName: 'DRUGS_COSMETICS_RULES_1945',
    sectionRef: 'Rule 106-A(1)(h)',
    title: 'Homoeopathic Mother Tincture — Manufacturing Licence Number',
    description: 'For products using or derived from a mother tincture, the manufacturing licence number of the mother tincture manufacturer must be declared on the label.',
    applicableCategories: HOMOEO_CATEGORIES,
    isMandatory: false,
    severity: 'MAJOR',
    effectiveVersion: '2026.1',
    effectiveDate: '1945-10-01',
  },
  {
    ruleId: 'DCR-R106B-PACKSIZE',
    actName: 'DRUGS_COSMETICS_RULES_1945',
    sectionRef: 'Rule 106-B',
    title: 'Homoeopathic Medicine — Pack Size Restriction (>12% Alcohol)',
    description: 'Homoeopathic preparations containing more than 12% alcohol by volume are subject to applicable pack size restrictions under Rule 106-B. The declared alcohol content must be verified against pack size.',
    applicableCategories: HOMOEO_CATEGORIES,
    isMandatory: false,
    severity: 'MAJOR',
    effectiveVersion: '2026.1',
    effectiveDate: '1945-10-01',
  },

  // ═══════════════════════════════════════════════════════════════════════════
  // MODULE K — ASU (Ayurvedic / Siddha / Unani) MEDICINES (D&C Rules, Rule 161)
  // ═══════════════════════════════════════════════════════════════════════════
  {
    ruleId: 'DCR-R161-INGREDIENTS',
    actName: 'DRUGS_COSMETICS_RULES_1945',
    sectionRef: 'Rule 161(1)(a)',
    title: 'ASU Medicine — True List of Ingredients',
    description: 'Every ASU medicine must bear a true list of ingredients, including botanical names of plant ingredients, plant parts used, form of ingredient, and quantity of each ingredient.',
    applicableCategories: ASU_CATEGORIES,
    isMandatory: true,
    severity: 'CRITICAL',
    effectiveVersion: '2026.1',
    effectiveDate: '1945-10-01',
  },
  {
    ruleId: 'DCR-R161-BOTANICAL',
    actName: 'DRUGS_COSMETICS_RULES_1945',
    sectionRef: 'Rule 161(1)(a)',
    title: 'ASU Medicine — Botanical Names of Plant Ingredients',
    description: 'Botanical (Latin scientific) names of plant ingredients must be declared alongside the common names on the label where required.',
    applicableCategories: ASU_CATEGORIES,
    isMandatory: true,
    severity: 'MAJOR',
    effectiveVersion: '2026.1',
    effectiveDate: '1945-10-01',
  },
  {
    ruleId: 'DCR-R161-DRUGNAME',
    actName: 'DRUGS_COSMETICS_RULES_1945',
    sectionRef: 'Rule 161(1)(b)',
    title: 'ASU Medicine — Name of Drug',
    description: 'The name of the ASU drug must be declared on the label.',
    applicableCategories: ASU_CATEGORIES,
    isMandatory: true,
    severity: 'CRITICAL',
    effectiveVersion: '2026.1',
    effectiveDate: '1945-10-01',
  },
  {
    ruleId: 'DCR-R161-NETCONTENT',
    actName: 'DRUGS_COSMETICS_RULES_1945',
    sectionRef: 'Rule 161(1)(c)',
    title: 'ASU Medicine — Correct Net Content in Metric Units',
    description: 'Net content of the ASU medicine must be declared in correct metric units.',
    applicableCategories: ASU_CATEGORIES,
    isMandatory: true,
    severity: 'CRITICAL',
    effectiveVersion: '2026.1',
    effectiveDate: '1945-10-01',
  },
  {
    ruleId: 'DCR-R161-MFGNAME',
    actName: 'DRUGS_COSMETICS_RULES_1945',
    sectionRef: 'Rule 161(1)(d)',
    title: 'ASU Medicine — Manufacturer Name & Address',
    description: 'Name and complete address of the manufacturer of the ASU medicine must be declared on the label.',
    applicableCategories: ASU_CATEGORIES,
    isMandatory: true,
    severity: 'CRITICAL',
    effectiveVersion: '2026.1',
    effectiveDate: '1945-10-01',
  },
  {
    ruleId: 'DCR-R161-LICNO',
    actName: 'DRUGS_COSMETICS_RULES_1945',
    sectionRef: 'Rule 161(1)(e)',
    title: 'ASU Medicine — Manufacturing Licence Number',
    description: 'The manufacturing licence number issued under the Drugs & Cosmetics Act must be declared on the label.',
    applicableCategories: ASU_CATEGORIES,
    isMandatory: true,
    severity: 'CRITICAL',
    effectiveVersion: '2026.1',
    effectiveDate: '1945-10-01',
  },
  {
    ruleId: 'DCR-R161-BATCHNO',
    actName: 'DRUGS_COSMETICS_RULES_1945',
    sectionRef: 'Rule 161(1)(f)',
    title: 'ASU Medicine — Batch / Lot Number',
    description: 'A distinctive Batch Number or Lot Number must be declared on the label of every ASU medicine.',
    applicableCategories: ASU_CATEGORIES,
    isMandatory: true,
    severity: 'CRITICAL',
    effectiveVersion: '2026.1',
    effectiveDate: '1945-10-01',
  },
  {
    ruleId: 'DCR-R161-MFGDATE',
    actName: 'DRUGS_COSMETICS_RULES_1945',
    sectionRef: 'Rule 161(1)(g)',
    title: 'ASU Medicine — Date of Manufacture',
    description: 'Date of manufacture (month and year) must be declared on the ASU medicine label.',
    applicableCategories: ASU_CATEGORIES,
    isMandatory: true,
    severity: 'MAJOR',
    effectiveVersion: '2026.1',
    effectiveDate: '1945-10-01',
  },
  {
    ruleId: 'DCR-R161-CATEGORY',
    actName: 'DRUGS_COSMETICS_RULES_1945',
    sectionRef: 'Rule 161(1)(h)',
    title: 'ASU Medicine — Category Declaration (Ayurvedic/Siddha/Unani)',
    description: 'The label must clearly state the applicable system: "Ayurvedic Medicine", "Siddha Medicine", or "Unani Medicine" as appropriate.',
    applicableCategories: ASU_CATEGORIES,
    isMandatory: true,
    severity: 'CRITICAL',
    effectiveVersion: '2026.1',
    effectiveDate: '1945-10-01',
  },
  {
    ruleId: 'DCR-R161-EXTERNALUSE',
    actName: 'DRUGS_COSMETICS_RULES_1945',
    sectionRef: 'Rule 161(1)(i)',
    title: 'ASU Medicine — "FOR EXTERNAL USE ONLY" (External Preparations)',
    description: 'ASU medicines intended for external use only must bear the declaration "FOR EXTERNAL USE ONLY" prominently on the label.',
    applicableCategories: ASU_CATEGORIES,
    isMandatory: false,
    severity: 'CRITICAL',
    effectiveVersion: '2026.1',
    effectiveDate: '1945-10-01',
  },
  {
    ruleId: 'DCR-R161-PRESERVATIVES',
    actName: 'DRUGS_COSMETICS_RULES_1945',
    sectionRef: 'Rule 161(1)(j)',
    title: 'ASU Medicine — Preservative & Colouring Agent Information',
    description: 'Where preservatives or colouring agents are used in an ASU medicine, their names and quantities must be declared on the label.',
    applicableCategories: ASU_CATEGORIES,
    isMandatory: false,
    severity: 'MAJOR',
    effectiveVersion: '2026.1',
    effectiveDate: '1945-10-01',
  },
  {
    ruleId: 'DCR-SCHE1-CAUTION',
    actName: 'DRUGS_COSMETICS_RULES_1945',
    sectionRef: 'Rule 161 & Schedule E(1)',
    title: 'ASU Medicine — Schedule E(1) Mandatory Caution',
    description: 'Where an ASU medicine contains a substance listed in Schedule E(1), the label must conspicuously display: "Caution: To be taken under medical supervision". This caution applies only where Schedule E(1) applicability is confirmed.',
    applicableCategories: ASU_CATEGORIES,
    isMandatory: false,
    severity: 'CRITICAL',
    effectiveVersion: '2026.1',
    effectiveDate: '1945-10-01',
    statutoryPenaltyRef: 'D&C Act Section 27',
  },
  {
    ruleId: 'DCR-R161B-EXPIRY',
    actName: 'DRUGS_COSMETICS_RULES_1945',
    sectionRef: 'Rule 161B',
    title: 'ASU Medicine — Shelf Life & Expiry Date Validation',
    description: 'The ASU medicine must declare date of expiry. Rule 161B prescribes category-specific shelf lives (e.g., tablets/capsules: 5 years; liquid preparations: 3 years; lehyam/avaleha: 3 years; ghrita/taila: 3 years; churna: 2 years; fresh plant juice: 1 year). Manufacturing date vs declared expiry must be validated.',
    applicableCategories: ASU_CATEGORIES,
    isMandatory: true,
    severity: 'CRITICAL',
    effectiveVersion: '2026.1',
    effectiveDate: '1945-10-01',
    statutoryPenaltyRef: 'D&C Act Section 27(b)',
  },

  // ═══════════════════════════════════════════════════════════════════════════
  // MODULE L — EXTENDED COSMETICS (D&C Rules 1945, Rule 148 / 148B)
  // ═══════════════════════════════════════════════════════════════════════════
  {
    ruleId: 'COSM-R148-NAME',
    actName: 'DRUGS_COSMETICS_RULES_1945',
    sectionRef: 'Rule 148(1)(a)',
    title: 'Cosmetic — Name of Cosmetic on Inner & Outer Label',
    description: 'The name of the cosmetic must appear on both the inner container and the outer label/package.',
    applicableCategories: COSMETIC_CATEGORIES,
    isMandatory: true,
    severity: 'CRITICAL',
    effectiveVersion: '2026.1',
    effectiveDate: '1945-10-01',
  },
  {
    ruleId: 'COSM-R148-MFGADDR',
    actName: 'DRUGS_COSMETICS_RULES_1945',
    sectionRef: 'Rule 148(1)(b)',
    title: 'Cosmetic — Complete Manufacturing Premises Address',
    description: 'Name of manufacturer and complete address of the manufacturing premises must be declared on the label. Small-container exceptions apply as per the rule.',
    applicableCategories: COSMETIC_CATEGORIES,
    isMandatory: true,
    severity: 'CRITICAL',
    effectiveVersion: '2026.1',
    effectiveDate: '1945-10-01',
  },
  {
    ruleId: 'COSM-R148-NETCONTENT',
    actName: 'DRUGS_COSMETICS_RULES_1945',
    sectionRef: 'Rule 148(2)',
    title: 'Cosmetic — Net Contents with Appropriate Unit Type',
    description: 'Net contents must be declared on the outer label: weight for solids/semi-solids; fluid measure for liquids; numerical count where applicable.',
    applicableCategories: COSMETIC_CATEGORIES,
    isMandatory: true,
    severity: 'MAJOR',
    effectiveVersion: '2026.1',
    effectiveDate: '1945-10-01',
  },
  {
    ruleId: 'COSM-R148-HAZARD',
    actName: 'DRUGS_COSMETICS_RULES_1945',
    sectionRef: 'Rule 148(3)',
    title: 'Cosmetic — Hazard Directions, Warnings & Cautions (When Applicable)',
    description: 'When a hazard exists, the inner label must contain: directions for safe use, warnings, cautions, special directions, and names & quantities of any hazardous or poisonous ingredients.',
    applicableCategories: COSMETIC_CATEGORIES,
    isMandatory: false,
    severity: 'CRITICAL',
    effectiveVersion: '2026.1',
    effectiveDate: '1945-10-01',
  },
  {
    ruleId: 'COSM-R148-BATCHPREFIX',
    actName: 'DRUGS_COSMETICS_RULES_1945',
    sectionRef: 'Rule 148(4) & Rule 34(1)(c)',
    title: 'Cosmetic — "B" Prefix on Batch Number',
    description: 'The distinctive batch number on cosmetic labels must be preceded by the letter "B" or the words "Batch No." Soap is exempted and may use month/year instead of batch number.',
    applicableCategories: COSMETIC_CATEGORIES,
    isMandatory: true,
    severity: 'MAJOR',
    effectiveVersion: '2026.1',
    effectiveDate: '1945-10-01',
  },
  {
    ruleId: 'COSM-R148-MFGLICPREFIX',
    actName: 'DRUGS_COSMETICS_RULES_1945',
    sectionRef: 'Rule 148(5)',
    title: 'Cosmetic — "M" Prefix on Manufacturing Licence Number',
    description: 'The manufacturing licence number on cosmetic labels must be preceded by the letter "M" (e.g., "Mfg Lic No. M-12345").',
    applicableCategories: COSMETIC_CATEGORIES,
    isMandatory: true,
    severity: 'MAJOR',
    effectiveVersion: '2026.1',
    effectiveDate: '1945-10-01',
  },
  {
    ruleId: 'COSM-R148B-FALSECLAIM',
    actName: 'DRUGS_COSMETICS_RULES_1945',
    sectionRef: 'Rule 148-B',
    title: 'Cosmetic — False or Misleading Claim (Rule 148B)',
    description: 'No cosmetic shall make a false or misleading claim on its label or in its labelling. Claims which purport to treat, cure, or materially alter the body beyond cosmetic effect may be considered misleading. Ordinary descriptive marketing language is not automatically flagged.',
    applicableCategories: COSMETIC_CATEGORIES,
    isMandatory: true,
    severity: 'MAJOR',
    effectiveVersion: '2026.1',
    effectiveDate: '1945-10-01',
    statutoryPenaltyRef: 'D&C Act Section 27(d)',
  },
  {
    ruleId: 'COSM-PROHIBITED-COLOUR',
    actName: 'DRUGS_COSMETICS_RULES_1945',
    sectionRef: 'Schedule Q & Rule 148-A',
    title: 'Cosmetic — Prohibited Colours / Lead & Arsenic Restrictions',
    description: 'Cosmetics must not contain: colours not permitted under Schedule Q; lead content exceeding permitted limits in colouring agents; arsenic exceeding permitted limits; or prohibited mercury compounds.',
    applicableCategories: COSMETIC_CATEGORIES,
    isMandatory: true,
    severity: 'CRITICAL',
    effectiveVersion: '2026.1',
    effectiveDate: '1945-10-01',
    statutoryPenaltyRef: 'D&C Act Section 27',
  },
  {
    ruleId: 'COSM-HEXACHLOROPHENE',
    actName: 'DRUGS_COSMETICS_RULES_1945',
    sectionRef: 'Rule 148-A & Schedule Q',
    title: 'Cosmetic — Hexachlorophene Restriction (Soap Exception)',
    description: 'Hexachlorophene is a restricted cosmetic ingredient. For soaps, it may be permitted with the applicable caution on the label. For non-soap cosmetics, its presence must be validated against permitted limits. Products must not exceed prescribed concentrations.',
    applicableCategories: COSMETIC_CATEGORIES,
    isMandatory: false,
    severity: 'CRITICAL',
    effectiveVersion: '2026.1',
    effectiveDate: '1945-10-01',
  },
  {
    ruleId: 'COSM-HAIRDYE-CAUTION',
    actName: 'DRUGS_COSMETICS_RULES_1945',
    sectionRef: 'Rule 148 & Schedule Q',
    title: 'Hair Dye — Mandatory Caution & Sensitivity Test Instruction',
    description: 'Hair dyes (products containing applicable dyes/colours/pigments for hair colouring) must bear: (a) a mandatory caution statement; (b) instruction to perform a preliminary patch/sensitivity test before use; (c) a prohibition against use on eyelashes or eyebrows.',
    applicableCategories: COSMETIC_CATEGORIES,
    isMandatory: false,
    severity: 'CRITICAL',
    effectiveVersion: '2026.1',
    effectiveDate: '1945-10-01',
  },
];

// Initialize and enforce ruleCategory, rule_category, and criticality on every rule
STATUTORY_RULES.forEach((r) => {
  if (!r.ruleCategory) {
    r.ruleCategory = resolveRuleCategory(r.ruleId, r.title, r.sectionRef);
  }
  r.rule_category = r.ruleCategory;
  if (!r.criticality) {
    r.criticality = isRuleCritical(r) ? 'CRITICAL' : 'NON_CRITICAL';
  }
});

