import { ProductCategory, ExtractedFields } from '../types';

export interface CategoryFieldConfig {
  key: keyof ExtractedFields | string;
  labelKey: string;
  defaultLabel: string;
  type: 'text' | 'number' | 'select';
  placeholder?: string;
  options?: { value: string; label: string }[];
  defaultValue?: string | number;
  required?: boolean;
  helpText?: string;
  gridSpan?: 1 | 2;
}

export interface StatutoryFrameworkRef {
  actCode: string;
  actTitle: string;
  sectionRef: string;
  shortDescription: string;
  badgeColor?: string;
}

export interface CommodityCategorySchema {
  category: ProductCategory;
  labelKey: string;
  displayName: string;
  shortDescription: string;
  applicableActs: StatutoryFrameworkRef[];
  fields: CategoryFieldConfig[];
  sampleProduct: Partial<ExtractedFields> & Record<string, any>;
  ruleCategories: ProductCategory[];
}

export const COMMODITY_SCHEMAS: Record<string, CommodityCategorySchema> = {
  PERSONAL_CARE_COSMETIC: {
    category: 'PERSONAL_CARE_COSMETIC',
    labelKey: 'categories.PERSONAL_CARE_COSMETIC',
    displayName: 'Cosmetics & Personal Care',
    shortDescription: 'Skincare, haircare, toiletries & cosmetic formulations under Cosmetics Rules 2020 & LM(PC) Rules 2011',
    applicableActs: [
      {
        actCode: 'LM_PC_2011',
        actTitle: 'Legal Metrology (Packaged Commodities) Rules, 2011',
        sectionRef: 'Rule 6(1)',
        shortDescription: 'Mandatory PDP declarations: Product generic name, net quantity, MRP, mfg date, and consumer grievance contact.',
        badgeColor: '#335E46',
      },
      {
        actCode: 'COSMETICS_RULES_2020',
        actTitle: 'Cosmetics Rules, 2020 (CDSCO)',
        sectionRef: 'Rule 34',
        shortDescription: 'Mandatory full INCI ingredient list in descending order, valid state/central Mfg License number, and expiry date.',
        badgeColor: '#52796F',
      },
      {
        actCode: 'CDSCO_DRUG_PROHIBITION',
        actTitle: 'Drugs and Cosmetics Act, 1940',
        sectionRef: 'Section 17C',
        shortDescription: 'Prohibition on making unauthorized medicinal/therapeutic claims on cosmetic labelling.',
        badgeColor: '#7A827B',
      },
    ],
    fields: [
      {
        key: 'productName',
        labelKey: 'rules.prodTitleLabel',
        defaultLabel: 'Product Name / Identity',
        type: 'text',
        placeholder: 'e.g. Aqualogica Radiance+ Dewy Sunscreen SPF 50',
        defaultValue: 'Aqualogica Radiance+ Dewy Sunscreen SPF 50 PA++++',
        required: true,
        gridSpan: 2,
      },
      {
        key: 'brandName',
        labelKey: 'workspace.brandName',
        defaultLabel: 'Brand Name',
        type: 'text',
        placeholder: 'e.g. Aqualogica',
        defaultValue: 'Aqualogica',
        required: false,
        gridSpan: 1,
      },
      {
        key: 'netQuantity',
        labelKey: 'rules.netQtyLabel',
        defaultLabel: 'Net Quantity',
        type: 'text',
        placeholder: 'e.g. 50.00 g / 100 ml',
        defaultValue: '50.00 g',
        required: true,
        gridSpan: 1,
      },
      {
        key: 'mrp',
        labelKey: 'rules.mrpLabel',
        defaultLabel: 'Maximum Retail Price (MRP)',
        type: 'text',
        placeholder: 'e.g. ₹ 399.00 (Incl. of all taxes)',
        defaultValue: '₹ 399.00',
        required: true,
        gridSpan: 1,
      },
      {
        key: 'cosmeticMfgLicense',
        labelKey: 'rules.cosmeticLicLabel',
        defaultLabel: 'Cosmetic Mfg License No.',
        type: 'text',
        placeholder: 'e.g. COS-LIC-HR-2022-901 or M-1234',
        defaultValue: 'COS-LIC-HR-2022-901',
        required: true,
        gridSpan: 1,
        helpText: 'Issued by State Licensing Authority / CDSCO under Form COS-8',
      },
      {
        key: 'cosmeticIngredients',
        labelKey: 'workspace.cosmeticIngredients',
        defaultLabel: 'INCI Ingredient List',
        type: 'text',
        placeholder: 'e.g. Aqua, Watermelon Extract, Niacinamide, Titanium Dioxide, Hyaluronic Acid',
        defaultValue: 'Aqua, Watermelon Extract, Niacinamide, Titanium Dioxide, Hyaluronic Acid, Ethylhexyl Methoxycinnamate',
        required: true,
        gridSpan: 2,
        helpText: 'Mandatory declaration in descending order of concentration (Rule 34)',
      },
      {
        key: 'mfgMonthYear',
        labelKey: 'workspace.mfgDate',
        defaultLabel: 'Date of Mfg / Packing',
        type: 'text',
        placeholder: 'e.g. AUG 2025 or 08/2025',
        defaultValue: 'AUG 2025',
        required: true,
        gridSpan: 1,
      },
      {
        key: 'expiryDate',
        labelKey: 'workspace.expiryDate',
        defaultLabel: 'Expiry / Use Before Date',
        type: 'text',
        placeholder: 'e.g. 08/2027',
        defaultValue: '08/2027',
        required: true,
        gridSpan: 1,
      },
      {
        key: 'batchNumber',
        labelKey: 'workspace.batchNumber',
        defaultLabel: 'Batch / Lot Number',
        type: 'text',
        placeholder: 'e.g. B-COS-2026-7719',
        defaultValue: 'B-COS-2026-7719',
        required: true,
        gridSpan: 1,
      },
      {
        key: 'consumerCarePhone',
        labelKey: 'rules.phoneLabel',
        defaultLabel: 'Consumer Care Helpline',
        type: 'text',
        placeholder: 'e.g. 1800-202-0040',
        defaultValue: '1800-202-0040',
        required: true,
        gridSpan: 1,
      },
      {
        key: 'manufacturerName',
        labelKey: 'workspace.manufacturer',
        defaultLabel: 'Manufacturer Name & Address',
        type: 'text',
        placeholder: 'e.g. Honasa Consumer Ltd, Gurugram, Haryana - 122003',
        defaultValue: 'Honasa Consumer Ltd, Sector 44, Gurugram, Haryana - 122003',
        required: true,
        gridSpan: 2,
      },
    ],
    sampleProduct: {
      productName: 'Aqualogica Radiance+ Dewy Sunscreen SPF 50 PA++++',
      brandName: 'Aqualogica',
      netQuantity: '50.00 g',
      mrp: '₹ 399.00',
      cosmeticMfgLicense: 'COS-LIC-HR-2022-901',
      cosmeticIngredients: 'Aqua, Watermelon Extract, Niacinamide, Titanium Dioxide, Hyaluronic Acid, Ethylhexyl Methoxycinnamate',
      mfgMonthYear: 'AUG 2025',
      expiryDate: '08/2027',
      batchNumber: 'B-COS-2026-7719',
      consumerCarePhone: '1800-202-0040',
      consumerCareEmail: 'care@aqualogica.in',
      manufacturerName: 'Honasa Consumer Limited',
      manufacturerAddress: 'Plot No. 63, Sector 44, Gurugram, Haryana - 122003',
    },
    ruleCategories: ['PERSONAL_CARE_COSMETIC'],
  },

  FOOD_BEVERAGE: {
    category: 'FOOD_BEVERAGE',
    labelKey: 'categories.FOOD_BEVERAGE',
    displayName: 'Food & Beverages',
    shortDescription: 'Pre-packaged food, confectionery, beverages & staples under FSSAI 2020 & LM(PC) Rules 2011',
    applicableActs: [
      {
        actCode: 'LM_PC_2011',
        actTitle: 'Legal Metrology (Packaged Commodities) Rules, 2011',
        sectionRef: 'Rule 6(1)',
        shortDescription: 'Product name, standard net quantity, MRP inclusive of taxes, unit sale price, and consumer helpline.',
        badgeColor: '#335E46',
      },
      {
        actCode: 'FSSAI_2020',
        actTitle: 'Food Safety and Standards (Labelling and Display) Regulations, 2020',
        sectionRef: 'Reg 5(1) & 5(4)',
        shortDescription: 'Mandatory 14-digit FSSAI License Number with Logo and Green/Brown Veg/Non-Veg symbolic declaration.',
        badgeColor: '#8C5E2D',
      },
    ],
    fields: [
      {
        key: 'productName',
        labelKey: 'rules.prodTitleLabel',
        defaultLabel: 'Product Name / Identity',
        type: 'text',
        placeholder: 'e.g. Britannia Good Day Butter Biscuits',
        defaultValue: 'Britannia Good Day Butter Biscuits',
        required: true,
        gridSpan: 2,
      },
      {
        key: 'brandName',
        labelKey: 'workspace.brandName',
        defaultLabel: 'Brand Name',
        type: 'text',
        placeholder: 'e.g. Britannia',
        defaultValue: 'Britannia',
        required: false,
        gridSpan: 1,
      },
      {
        key: 'netQuantity',
        labelKey: 'rules.netQtyLabel',
        defaultLabel: 'Net Quantity',
        type: 'text',
        placeholder: 'e.g. 200 g / 1 kg',
        defaultValue: '200 g',
        required: true,
        gridSpan: 1,
      },
      {
        key: 'mrp',
        labelKey: 'rules.mrpLabel',
        defaultLabel: 'Maximum Retail Price (MRP)',
        type: 'text',
        placeholder: 'e.g. ₹ 40.00',
        defaultValue: '₹ 40.00',
        required: true,
        gridSpan: 1,
      },
      {
        key: 'fssaiLicenseNumber',
        labelKey: 'rules.fssaiLicLabel',
        defaultLabel: '14-Digit FSSAI License No.',
        type: 'text',
        placeholder: 'e.g. 10015043001290',
        defaultValue: '10015043001290',
        required: true,
        gridSpan: 1,
        helpText: 'Mandatory 14-digit Food Safety Authority licence number',
      },
      {
        key: 'vegNonVegMark',
        labelKey: 'workspace.vegNonVeg',
        defaultLabel: 'Veg / Non-Veg Standard Symbol',
        type: 'select',
        options: [
          { value: 'VEG', label: 'Vegetarian (Green Circle in Square)' },
          { value: 'NON_VEG', label: 'Non-Vegetarian (Brown Triangle in Square)' },
        ],
        defaultValue: 'VEG',
        required: true,
        gridSpan: 1,
      },
      {
        key: 'mfgMonthYear',
        labelKey: 'workspace.mfgDate',
        defaultLabel: 'Date of Packing / Mfg',
        type: 'text',
        placeholder: 'e.g. 10/2025',
        defaultValue: '10/2025',
        required: true,
        gridSpan: 1,
      },
      {
        key: 'consumerCarePhone',
        labelKey: 'rules.phoneLabel',
        defaultLabel: 'Consumer Care Helpline',
        type: 'text',
        placeholder: 'e.g. 1800-425-4449',
        defaultValue: '1800-425-4449',
        required: true,
        gridSpan: 1,
      },
      {
        key: 'manufacturerName',
        labelKey: 'workspace.manufacturer',
        defaultLabel: 'Manufacturer Name & Complete Address',
        type: 'text',
        placeholder: 'e.g. Britannia Industries Ltd, Bengaluru, Karnataka - 560047',
        defaultValue: 'Britannia Industries Ltd, 5/1A Hungerford Street, Kolkata - 700017',
        required: true,
        gridSpan: 2,
      },
    ],
    sampleProduct: {
      productName: 'Britannia Good Day Butter Biscuits',
      brandName: 'Britannia',
      netQuantity: '200 g',
      mrp: '₹ 40.00',
      fssaiLicenseNumber: '10015043001290',
      vegNonVegMark: 'VEG',
      mfgMonthYear: '10/2025',
      consumerCarePhone: '1800-425-4449',
      consumerCareEmail: 'feedback@britindia.com',
      manufacturerName: 'Britannia Industries Ltd',
      manufacturerAddress: '5/1A Hungerford Street, Kolkata, West Bengal - 700017',
    },
    ruleCategories: ['FOOD_BEVERAGE'],
  },

  STATIONERY_OFFICE: {
    category: 'STATIONERY_OFFICE',
    labelKey: 'categories.STATIONERY_OFFICE',
    displayName: 'Stationery & Office Supplies',
    shortDescription: 'Pens, notebooks, paper, desk instruments & general packaged consumer goods under LM(PC) Rules 2011',
    applicableActs: [
      {
        actCode: 'LM_PC_2011',
        actTitle: 'Legal Metrology (Packaged Commodities) Rules, 2011',
        sectionRef: 'Rule 6(1)',
        shortDescription: 'Core statutory metrology declarations: Generic commodity identity, net quantity/count, MRP with Unit Sale Price, complete manufacturer PIN address, and consumer care.',
        badgeColor: '#335E46',
      },
      {
        actCode: 'LM_PC_RULE6_2',
        actTitle: 'LM(PC) Unit Sale Price (USP) Amendment',
        sectionRef: 'Rule 6(2)',
        shortDescription: 'Mandatory Unit Sale Price (e.g. ₹ 10.00/N) declared whenever package contains multi-unit items.',
        badgeColor: '#52796F',
      },
    ],
    fields: [
      {
        key: 'productName',
        labelKey: 'rules.prodTitleLabel',
        defaultLabel: 'Product Generic Identity / Name',
        type: 'text',
        placeholder: 'e.g. Reynolds Fine Writing Ball Pen (Pack of 10)',
        defaultValue: 'Reynolds Fine Writing Ball Pen (Pack of 10 Blue)',
        required: true,
        gridSpan: 2,
      },
      {
        key: 'brandName',
        labelKey: 'workspace.brandName',
        defaultLabel: 'Brand Name',
        type: 'text',
        placeholder: 'e.g. Reynolds India',
        defaultValue: 'Reynolds India',
        required: false,
        gridSpan: 1,
      },
      {
        key: 'netQuantity',
        labelKey: 'rules.netQtyLabel',
        defaultLabel: 'Net Quantity / Count',
        type: 'text',
        placeholder: 'e.g. 10 N or 1 N',
        defaultValue: '10 N',
        required: true,
        gridSpan: 1,
        helpText: 'In standard units of number (N) or count under Second Schedule',
      },
      {
        key: 'mrp',
        labelKey: 'rules.mrpLabel',
        defaultLabel: 'Maximum Retail Price (MRP)',
        type: 'text',
        placeholder: 'e.g. ₹ 100.00',
        defaultValue: '₹ 100.00',
        required: true,
        gridSpan: 1,
      },
      {
        key: 'unitSalePrice',
        labelKey: 'workspace.unitSalePrice',
        defaultLabel: 'Unit Sale Price (USP)',
        type: 'text',
        placeholder: 'e.g. ₹ 10.00/N',
        defaultValue: '₹ 10.00/N',
        required: true,
        gridSpan: 1,
        helpText: 'Mandatory for multi-unit packages under Rule 6(2)',
      },
      {
        key: 'mfgMonthYear',
        labelKey: 'workspace.mfgDate',
        defaultLabel: 'Date of Packing / Mfg',
        type: 'text',
        placeholder: 'e.g. AUG 2025',
        defaultValue: 'AUG 2025',
        required: true,
        gridSpan: 1,
      },
      {
        key: 'consumerCarePhone',
        labelKey: 'rules.phoneLabel',
        defaultLabel: 'Consumer Care Helpline',
        type: 'text',
        placeholder: 'e.g. 1800-200-7890',
        defaultValue: '1800-200-7890',
        required: true,
        gridSpan: 1,
      },
      {
        key: 'manufacturerName',
        labelKey: 'workspace.manufacturer',
        defaultLabel: 'Manufacturer Name & Complete Address with PIN',
        type: 'text',
        placeholder: 'e.g. Reynolds Writing Instruments Pvt Ltd, Sriperumbudur, Tamil Nadu - 602105',
        defaultValue: 'Reynolds Writing Instruments Pvt Ltd, Plot 12, SIPCOT Industrial Park, Sriperumbudur, Tamil Nadu - 602105',
        required: true,
        gridSpan: 2,
      },
    ],
    sampleProduct: {
      productName: 'Reynolds Fine Writing Ball Pen (Pack of 10 Blue)',
      brandName: 'Reynolds India',
      netQuantity: '10 N',
      unitSalePrice: '₹ 10.00/N',
      mrp: '₹ 100.00',
      mfgMonthYear: 'AUG 2025',
      batchNumber: 'BATCH-STN-2026-101',
      consumerCarePhone: '1800-200-7890',
      consumerCareEmail: 'support@reynolds.in',
      manufacturerName: 'Reynolds Writing Instruments Pvt Ltd',
      manufacturerAddress: 'Plot 12, SIPCOT Industrial Park, Sriperumbudur, Tamil Nadu - 602105',
    },
    ruleCategories: ['STATIONERY_OFFICE'],
  },

  SEED_AGRICULTURE: {
    category: 'SEED_AGRICULTURE',
    labelKey: 'categories.SEED_AGRICULTURE',
    displayName: 'Agricultural Seeds',
    shortDescription: 'Certified & notified crop seeds under The Seeds Act 1966, Seeds Rules 1968 & LM(PC) Rules 2011',
    applicableActs: [
      {
        actCode: 'LM_PC_2011',
        actTitle: 'Legal Metrology (Packaged Commodities) Rules, 2011',
        sectionRef: 'Rule 6(1)',
        shortDescription: 'Standard package net quantity in kg/g, MRP, packer name/address, and consumer grievance contact.',
        badgeColor: '#335E46',
      },
      {
        actCode: 'SEEDS_ACT_1966',
        actTitle: 'The Seeds Act, 1966 & Seeds Rules, 1968',
        sectionRef: 'Section 6(a) & Rule 7',
        shortDescription: 'Strict statutory minimum germination percentage (e.g. 85% for Hybrid Maize), genetic purity (98%+), and 9-month test validity tag.',
        badgeColor: '#8C5E2D',
      },
      {
        actCode: 'CENTRAL_SEED_COMMITTEE',
        actTitle: 'Central Seed Committee Notification Standards',
        sectionRef: 'Rule 10',
        shortDescription: 'Class of seed tag (Certified/Foundation), official Lot Number, and seed inspector analysis certification.',
        badgeColor: '#52796F',
      },
    ],
    fields: [
      {
        key: 'productName',
        labelKey: 'rules.prodTitleLabel',
        defaultLabel: 'Seed Variety / Crop Name',
        type: 'text',
        placeholder: 'e.g. Certified Hybrid Maize Seed KM-901',
        defaultValue: 'Certified Hybrid Maize Seed KM-901 (Kisan Hybrid)',
        required: true,
        gridSpan: 2,
      },
      {
        key: 'brandName',
        labelKey: 'workspace.brandName',
        defaultLabel: 'Seed Producer / Brand',
        type: 'text',
        placeholder: 'e.g. Kisan Agri Inputs',
        defaultValue: 'Kisan Agri Inputs Ltd',
        required: false,
        gridSpan: 1,
      },
      {
        key: 'netQuantity',
        labelKey: 'rules.netQtyLabel',
        defaultLabel: 'Net Weight',
        type: 'text',
        placeholder: 'e.g. 4.00 kg',
        defaultValue: '4.00 kg',
        required: true,
        gridSpan: 1,
      },
      {
        key: 'mrp',
        labelKey: 'rules.mrpLabel',
        defaultLabel: 'Maximum Retail Price (MRP)',
        type: 'text',
        placeholder: 'e.g. ₹ 950.00',
        defaultValue: '₹ 950.00',
        required: true,
        gridSpan: 1,
      },
      {
        key: 'germinationPercentage',
        labelKey: 'rules.germinationLabel',
        defaultLabel: 'Minimum Germination % (Seeds Act Sec 6a)',
        type: 'number',
        placeholder: 'e.g. 85',
        defaultValue: 85,
        required: true,
        gridSpan: 1,
        helpText: 'Statutory national minimum for notified hybrid maize is 85.0%',
      },
      {
        key: 'geneticPurityPercentage',
        labelKey: 'workspace.geneticPurity',
        defaultLabel: 'Genetic / Physical Purity %',
        type: 'number',
        placeholder: 'e.g. 98.0',
        defaultValue: 98.5,
        required: true,
        gridSpan: 1,
        helpText: 'Section 6(a) prescribes 98.0% minimum physical and genetic purity',
      },
      {
        key: 'lotNumber',
        labelKey: 'workspace.lotNumber',
        defaultLabel: 'Seed Lot Number & Tag ID',
        type: 'text',
        placeholder: 'e.g. LOT-KM-MZ-2026-891',
        defaultValue: 'LOT-KM-MZ-2026-891',
        required: true,
        gridSpan: 1,
      },
      {
        key: 'consumerCarePhone',
        labelKey: 'rules.phoneLabel',
        defaultLabel: 'Farmer Care Helpline',
        type: 'text',
        placeholder: 'e.g. 1800-180-1551',
        defaultValue: '1800-180-1551',
        required: true,
        gridSpan: 1,
      },
      {
        key: 'manufacturerName',
        labelKey: 'workspace.manufacturer',
        defaultLabel: 'Seed Producer / Processing Plant Address',
        type: 'text',
        placeholder: 'e.g. Kisan Agri Inputs Pvt Ltd, GT Road, Karnal, Haryana - 132001',
        defaultValue: 'Kisan Agri Inputs Pvt Ltd, Industrial Area, GT Road, Karnal, Haryana - 132001',
        required: true,
        gridSpan: 2,
      },
    ],
    sampleProduct: {
      productName: 'Certified Hybrid Maize Seed KM-901 (Kisan Hybrid)',
      brandName: 'Kisan Agri Inputs Ltd',
      netQuantity: '4.00 kg',
      mrp: '₹ 950.00',
      germinationPercentage: 85.0,
      geneticPurityPercentage: 98.5,
      lotNumber: 'LOT-KM-MZ-2026-891',
      dateOfTest: 'OCT-2025',
      seedClass: 'Certified Hybrid F1 Seed',
      consumerCarePhone: '1800-180-1551',
      consumerCareEmail: 'support@kisanseed.in',
      manufacturerName: 'Kisan Agri Inputs Pvt Ltd',
      manufacturerAddress: 'Industrial Area, GT Road, Karnal, Haryana - 132001',
    },
    ruleCategories: ['SEED_AGRICULTURE'],
  },

  FERTILIZER_CHEMICAL: {
    category: 'FERTILIZER_CHEMICAL',
    labelKey: 'categories.FERTILIZER_CHEMICAL',
    displayName: 'Chemical & Bio Fertilizers',
    shortDescription: 'Plant nutrients, chemical grades & bio-fertilizers under Fertilizer Control Order 1985 & LM(PC) Rules',
    applicableActs: [
      {
        actCode: 'LM_PC_2011',
        actTitle: 'Legal Metrology (Packaged Commodities) Rules, 2011',
        sectionRef: 'Rule 6(1)',
        shortDescription: 'Net weight, standard bagged tolerances, MRP inclusive of taxes, and producer contact.',
        badgeColor: '#335E46',
      },
      {
        actCode: 'FCO_1985',
        actTitle: 'Fertilizer Control Order (FCO), 1985',
        sectionRef: 'Clause 19 & Sched 1',
        shortDescription: 'Guaranteed NPK nutrient formulation (Clause 19) matching statutory Schedule 1 specifications and moisture limits.',
        badgeColor: '#8C5E2D',
      },
      {
        actCode: 'BIS_IS5406',
        actTitle: 'Bureau of Indian Standards (IS:5406)',
        sectionRef: 'Clause 21',
        shortDescription: 'Mandatory BIS / ISI Certification Mark and State Fertilizer Manufacturer License number on every bag.',
        badgeColor: '#52796F',
      },
    ],
    fields: [
      {
        key: 'productName',
        labelKey: 'rules.prodTitleLabel',
        defaultLabel: 'Fertilizer Product / Grade Name',
        type: 'text',
        placeholder: 'e.g. IFFCO NPK 19:19:19 Water Soluble Fertilizer',
        defaultValue: 'IFFCO NPK 19:19:19 100% Water Soluble Complex Fertilizer',
        required: true,
        gridSpan: 2,
      },
      {
        key: 'brandName',
        labelKey: 'workspace.brandName',
        defaultLabel: 'Manufacturer / Brand',
        type: 'text',
        placeholder: 'e.g. IFFCO',
        defaultValue: 'IFFCO Plant Nutrients',
        required: false,
        gridSpan: 1,
      },
      {
        key: 'netQuantity',
        labelKey: 'rules.netQtyLabel',
        defaultLabel: 'Net Weight',
        type: 'text',
        placeholder: 'e.g. 1.00 kg or 50.00 kg',
        defaultValue: '1.00 kg',
        required: true,
        gridSpan: 1,
      },
      {
        key: 'mrp',
        labelKey: 'rules.mrpLabel',
        defaultLabel: 'Maximum Retail Price (MRP)',
        type: 'text',
        placeholder: 'e.g. ₹ 210.00',
        defaultValue: '₹ 210.00',
        required: true,
        gridSpan: 1,
      },
      {
        key: 'npkRatio',
        labelKey: 'rules.npkRatioLabel',
        defaultLabel: 'Guaranteed NPK Nutrient Ratio (FCO Sched 1)',
        type: 'text',
        placeholder: 'e.g. 19:19:19',
        defaultValue: '19:19:19',
        required: true,
        gridSpan: 1,
        helpText: 'Mandatory declared grade ratio under FCO 1985 Schedule 1',
      },
      {
        key: 'fcoLicenseNumber',
        labelKey: 'workspace.fcoLicense',
        defaultLabel: 'State FCO Mfg License No.',
        type: 'text',
        placeholder: 'e.g. FCO-LIC-UP-VAR-902',
        defaultValue: 'FCO-LIC-UP-VAR-902',
        required: true,
        gridSpan: 1,
      },
      {
        key: 'isiMarkNumber',
        labelKey: 'rules.bisMarkLabel',
        defaultLabel: 'BIS / ISI Certification Mark (IS:5406)',
        type: 'text',
        placeholder: 'e.g. IS 5406 (CM/L-780123)',
        defaultValue: 'IS 5406 (CM/L-780123)',
        required: true,
        gridSpan: 1,
      },
      {
        key: 'consumerCarePhone',
        labelKey: 'rules.phoneLabel',
        defaultLabel: 'Farmer Grievance Helpline',
        type: 'text',
        placeholder: 'e.g. 1800-103-1967',
        defaultValue: '1800-103-1967',
        required: true,
        gridSpan: 1,
      },
      {
        key: 'manufacturerName',
        labelKey: 'workspace.manufacturer',
        defaultLabel: 'Manufacturer Name & Address',
        type: 'text',
        placeholder: 'e.g. Indian Farmers Fertiliser Cooperative Ltd (IFFCO), New Delhi - 110017',
        defaultValue: 'Indian Farmers Fertiliser Cooperative Ltd, IFFCO Sadan, Saket, New Delhi - 110017',
        required: true,
        gridSpan: 2,
      },
    ],
    sampleProduct: {
      productName: 'IFFCO NPK 19:19:19 100% Water Soluble Complex Fertilizer',
      brandName: 'IFFCO Plant Nutrients',
      netQuantity: '1.00 kg',
      mrp: '₹ 210.00',
      npkRatio: '19:19:19',
      fcoLicenseNumber: 'FCO-LIC-UP-VAR-902',
      isiMarkNumber: 'IS 5406 (CM/L-780123)',
      consumerCarePhone: '1800-103-1967',
      consumerCareEmail: 'customercare@iffco.in',
      manufacturerName: 'Indian Farmers Fertiliser Cooperative Ltd (IFFCO)',
      manufacturerAddress: 'IFFCO Sadan, C-1, District Centre, Saket, New Delhi - 110017',
    },
    ruleCategories: ['FERTILIZER_CHEMICAL'],
  },

  ELECTRONICS: {
    category: 'ELECTRONICS',
    labelKey: 'categories.ELECTRONICS',
    displayName: 'Consumer Electronics',
    shortDescription: 'Electronic appliances, IT goods & lighting under BIS CRO 2012 & LM(PC) Rules 2011',
    applicableActs: [
      {
        actCode: 'LM_PC_2011',
        actTitle: 'Legal Metrology (Packaged Commodities) Rules, 2011',
        sectionRef: 'Rule 6(1)',
        shortDescription: 'Generic product identity, model name, net quantity, MRP, mfg date, importer/manufacturer PIN details, consumer care.',
        badgeColor: '#335E46',
      },
      {
        actCode: 'BIS_CRO_2012',
        actTitle: 'BIS Compulsory Registration Scheme (CRO 2012)',
        sectionRef: 'IS 16102 / Rule 6',
        shortDescription: 'Mandatory BIS Registration mark (R-XXXXXXXX) and BEE Star Energy Rating label where applicable.',
        badgeColor: '#52796F',
      },
    ],
    fields: [
      {
        key: 'productName',
        labelKey: 'rules.prodTitleLabel',
        defaultLabel: 'Product Name / Model',
        type: 'text',
        placeholder: 'e.g. Havells Lumeno LED Lamp 9W Cool Day Light',
        defaultValue: 'Havells Lumeno LED Lamp 9W Cool Day Light (B22)',
        required: true,
        gridSpan: 2,
      },
      {
        key: 'brandName',
        labelKey: 'workspace.brandName',
        defaultLabel: 'Brand Name',
        type: 'text',
        placeholder: 'e.g. Havells',
        defaultValue: 'Havells India',
        required: false,
        gridSpan: 1,
      },
      {
        key: 'netQuantity',
        labelKey: 'rules.netQtyLabel',
        defaultLabel: 'Net Quantity',
        type: 'text',
        placeholder: 'e.g. 1 N',
        defaultValue: '1 N',
        required: true,
        gridSpan: 1,
      },
      {
        key: 'mrp',
        labelKey: 'rules.mrpLabel',
        defaultLabel: 'Maximum Retail Price (MRP)',
        type: 'text',
        placeholder: 'e.g. ₹ 140.00',
        defaultValue: '₹ 140.00',
        required: true,
        gridSpan: 1,
      },
      {
        key: 'isiMarkNumber',
        labelKey: 'rules.bisMarkLabel',
        defaultLabel: 'BIS Registration No. (R-XXXXXXXX)',
        type: 'text',
        placeholder: 'e.g. R-41012345 (IS 16102)',
        defaultValue: 'R-41012345 (IS 16102 Part 1)',
        required: true,
        gridSpan: 1,
      },
      {
        key: 'mfgMonthYear',
        labelKey: 'workspace.mfgDate',
        defaultLabel: 'Month & Year of Manufacture',
        type: 'text',
        placeholder: 'e.g. 09/2025',
        defaultValue: '09/2025',
        required: true,
        gridSpan: 1,
      },
      {
        key: 'consumerCarePhone',
        labelKey: 'rules.phoneLabel',
        defaultLabel: 'Consumer Service Helpline',
        type: 'text',
        placeholder: 'e.g. 1800-103-1313',
        defaultValue: '1800-103-1313',
        required: true,
        gridSpan: 1,
      },
      {
        key: 'manufacturerName',
        labelKey: 'workspace.manufacturer',
        defaultLabel: 'Manufacturer / Importer Address with PIN',
        type: 'text',
        placeholder: 'e.g. Havells India Ltd, Sector 59, Noida, UP - 201301',
        defaultValue: 'Havells India Ltd, 904, Surya Kiran Building, K.G. Marg, New Delhi - 110001',
        required: true,
        gridSpan: 2,
      },
    ],
    sampleProduct: {
      productName: 'Havells Lumeno LED Lamp 9W Cool Day Light (B22)',
      brandName: 'Havells India',
      netQuantity: '1 N',
      mrp: '₹ 140.00',
      isiMarkNumber: 'R-41012345 (IS 16102 Part 1)',
      mfgMonthYear: '09/2025',
      consumerCarePhone: '1800-103-1313',
      consumerCareEmail: 'customercare@havells.com',
      manufacturerName: 'Havells India Ltd',
      manufacturerAddress: 'Surya Kiran Building, K.G. Marg, New Delhi - 110001',
    },
    ruleCategories: ['ELECTRONICS'],
  },

  TOYS_CHILDREN: {
    category: 'TOYS_CHILDREN',
    labelKey: 'categories.TOYS_CHILDREN',
    displayName: 'Toys & Children Goods',
    shortDescription: 'Toys, educational games & playthings under Toys (Quality Control) Order 2020 & LM(PC) Rules',
    applicableActs: [
      {
        actCode: 'LM_PC_2011',
        actTitle: 'Legal Metrology (Packaged Commodities) Rules, 2011',
        sectionRef: 'Rule 6(1)',
        shortDescription: 'Product generic identity, net count, MRP, mfg date, domestic manufacturer or importer address, consumer care.',
        badgeColor: '#335E46',
      },
      {
        actCode: 'TOYS_QCO_2020',
        actTitle: 'Toys (Quality Control) Order, 2020',
        sectionRef: 'IS 9873 / Scheme I',
        shortDescription: 'Mandatory Bureau of Indian Standards ISI Mark (IS 9873) and clear age suitability / choking hazard warnings.',
        badgeColor: '#9E432A',
      },
    ],
    fields: [
      {
        key: 'productName',
        labelKey: 'rules.prodTitleLabel',
        defaultLabel: 'Toy Product Identity',
        type: 'text',
        placeholder: 'e.g. Funskool Educational Building Blocks (Set of 60)',
        defaultValue: 'Funskool Educational Creative Building Blocks (60 Pcs)',
        required: true,
        gridSpan: 2,
      },
      {
        key: 'brandName',
        labelKey: 'workspace.brandName',
        defaultLabel: 'Brand Name',
        type: 'text',
        placeholder: 'e.g. Funskool',
        defaultValue: 'Funskool India',
        required: false,
        gridSpan: 1,
      },
      {
        key: 'netQuantity',
        labelKey: 'rules.netQtyLabel',
        defaultLabel: 'Net Count / Quantity',
        type: 'text',
        placeholder: 'e.g. 1 Set (60 N)',
        defaultValue: '1 Set (60 N)',
        required: true,
        gridSpan: 1,
      },
      {
        key: 'mrp',
        labelKey: 'rules.mrpLabel',
        defaultLabel: 'Maximum Retail Price (MRP)',
        type: 'text',
        placeholder: 'e.g. ₹ 499.00',
        defaultValue: '₹ 499.00',
        required: true,
        gridSpan: 1,
      },
      {
        key: 'isiMarkNumber',
        labelKey: 'rules.bisMarkLabel',
        defaultLabel: 'BIS Safety Standard Mark (IS 9873)',
        type: 'text',
        placeholder: 'e.g. ISI IS 9873 Part 1 (CM/L-654321)',
        defaultValue: 'ISI IS 9873 Part 1 (CM/L-654321)',
        required: true,
        gridSpan: 1,
      },
      {
        key: 'mfgMonthYear',
        labelKey: 'workspace.mfgDate',
        defaultLabel: 'Date of Packing / Mfg',
        type: 'text',
        placeholder: 'e.g. 07/2025',
        defaultValue: '07/2025',
        required: true,
        gridSpan: 1,
      },
      {
        key: 'consumerCarePhone',
        labelKey: 'rules.phoneLabel',
        defaultLabel: 'Consumer Care Helpline',
        type: 'text',
        placeholder: 'e.g. 1800-425-3333',
        defaultValue: '1800-425-3333',
        required: true,
        gridSpan: 1,
      },
      {
        key: 'manufacturerName',
        labelKey: 'workspace.manufacturer',
        defaultLabel: 'Manufacturer Address with PIN',
        type: 'text',
        placeholder: 'e.g. Funskool India Ltd, Tarapore Towers, Chennai - 600002',
        defaultValue: 'Funskool India Ltd, Tarapore Towers, 826 Anna Salai, Chennai, Tamil Nadu - 600002',
        required: true,
        gridSpan: 2,
      },
    ],
    sampleProduct: {
      productName: 'Funskool Educational Creative Building Blocks (60 Pcs)',
      brandName: 'Funskool India',
      netQuantity: '1 Set (60 N)',
      mrp: '₹ 499.00',
      isiMarkNumber: 'ISI IS 9873 Part 1 (CM/L-654321)',
      mfgMonthYear: '07/2025',
      consumerCarePhone: '1800-425-3333',
      consumerCareEmail: 'support@funskool.co.in',
      manufacturerName: 'Funskool India Ltd',
      manufacturerAddress: 'Tarapore Towers, 826 Anna Salai, Chennai, Tamil Nadu - 600002',
    },
    ruleCategories: ['TOYS_CHILDREN'],
  },

  HOUSEHOLD_COMMODITY: {
    category: 'HOUSEHOLD_COMMODITY',
    labelKey: 'categories.HOUSEHOLD_COMMODITY',
    displayName: 'Household Commodities',
    shortDescription: 'Detergents, cleaning products, home maintenance & FMCG under LM(PC) Rules 2011',
    applicableActs: [
      {
        actCode: 'LM_PC_2011',
        actTitle: 'Legal Metrology (Packaged Commodities) Rules, 2011',
        sectionRef: 'Rule 6(1)',
        shortDescription: 'Generic name, net quantity in standard SI units, MRP with Unit Sale Price, complete manufacturer PIN address, consumer helpline.',
        badgeColor: '#335E46',
      },
    ],
    fields: [
      {
        key: 'productName',
        labelKey: 'rules.prodTitleLabel',
        defaultLabel: 'Product Name / Identity',
        type: 'text',
        placeholder: 'e.g. Surf Excel Easy Wash Detergent Powder',
        defaultValue: 'Surf Excel Easy Wash Detergent Powder',
        required: true,
        gridSpan: 2,
      },
      {
        key: 'brandName',
        labelKey: 'workspace.brandName',
        defaultLabel: 'Brand Name',
        type: 'text',
        placeholder: 'e.g. Surf Excel',
        defaultValue: 'Surf Excel',
        required: false,
        gridSpan: 1,
      },
      {
        key: 'netQuantity',
        labelKey: 'rules.netQtyLabel',
        defaultLabel: 'Net Quantity',
        type: 'text',
        placeholder: 'e.g. 1.00 kg',
        defaultValue: '1.00 kg',
        required: true,
        gridSpan: 1,
      },
      {
        key: 'mrp',
        labelKey: 'rules.mrpLabel',
        defaultLabel: 'Maximum Retail Price (MRP)',
        type: 'text',
        placeholder: 'e.g. ₹ 145.00',
        defaultValue: '₹ 145.00',
        required: true,
        gridSpan: 1,
      },
      {
        key: 'unitSalePrice',
        labelKey: 'workspace.unitSalePrice',
        defaultLabel: 'Unit Sale Price (USP)',
        type: 'text',
        placeholder: 'e.g. ₹ 145.00/kg',
        defaultValue: '₹ 145.00/kg',
        required: true,
        gridSpan: 1,
      },
      {
        key: 'mfgMonthYear',
        labelKey: 'workspace.mfgDate',
        defaultLabel: 'Date of Packing / Mfg',
        type: 'text',
        placeholder: 'e.g. 08/2025',
        defaultValue: '08/2025',
        required: true,
        gridSpan: 1,
      },
      {
        key: 'consumerCarePhone',
        labelKey: 'rules.phoneLabel',
        defaultLabel: 'Consumer Care Helpline',
        type: 'text',
        placeholder: 'e.g. 1800-10-22-221',
        defaultValue: '1800-10-22-221',
        required: true,
        gridSpan: 1,
      },
      {
        key: 'manufacturerName',
        labelKey: 'workspace.manufacturer',
        defaultLabel: 'Manufacturer Name & Address with PIN',
        type: 'text',
        placeholder: 'e.g. Hindustan Unilever Ltd, B.D. Sawant Marg, Mumbai - 400099',
        defaultValue: 'Hindustan Unilever Ltd, Unilever House, B.D. Sawant Marg, Chakala, Andheri (E), Mumbai - 400099',
        required: true,
        gridSpan: 2,
      },
    ],
    sampleProduct: {
      productName: 'Surf Excel Easy Wash Detergent Powder',
      brandName: 'Surf Excel',
      netQuantity: '1.00 kg',
      unitSalePrice: '₹ 145.00/kg',
      mrp: '₹ 145.00',
      mfgMonthYear: '08/2025',
      consumerCarePhone: '1800-10-22-221',
      consumerCareEmail: 'lever.care@unilever.com',
      manufacturerName: 'Hindustan Unilever Ltd',
      manufacturerAddress: 'Unilever House, B.D. Sawant Marg, Chakala, Andheri (E), Mumbai - 400099',
    },
    ruleCategories: ['HOUSEHOLD_COMMODITY'],
  },
};

export const SUPPORTED_SANDBOX_CATEGORIES: ProductCategory[] = [
  'PERSONAL_CARE_COSMETIC',
  'FOOD_BEVERAGE',
  'STATIONERY_OFFICE',
  'SEED_AGRICULTURE',
  'FERTILIZER_CHEMICAL',
  'ELECTRONICS',
  'TOYS_CHILDREN',
  'HOUSEHOLD_COMMODITY',
];

/**
 * Helper to safely fetch schema for any category or fallback to STATIONERY_OFFICE / general
 */
export function getCategorySchema(category: ProductCategory): CommodityCategorySchema {
  if (COMMODITY_SCHEMAS[category]) {
    return COMMODITY_SCHEMAS[category];
  }
  return COMMODITY_SCHEMAS['STATIONERY_OFFICE'];
}

/**
 * Returns human-readable statutory frameworks summary for an inspection or category
 */
export function getApplicableActsSummary(category: ProductCategory): string {
  const schema = getCategorySchema(category);
  return schema.applicableActs.map((act) => act.actTitle).join(' • ');
}
